export { endpoint as globalMarketCap } from './globalMarketCap'
export { endpoint as dominance } from './dominance'
export { endpoint as historical } from './historical'
export { endpoint as crypto } from './crypto'
export { endpoint as marketcap } from './marketcap'
export { endpoint as volume } from './volume'
