import nock from 'nock'

export const mockGamesResponse = (key: string) => {
  nock('https://fly.sportsdata.io:443', { encodedQueryParams: true })
    .get('/v3/mlb/scores/json/GamesByDate/2017-JUL-31')
    .query({ key })
    .reply(
      200,
      [
        {
          GameID: 49127,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T12:35:00',
          AwayTeam: 'ATL',
          HomeTeam: 'PHI',
          AwayTeamID: 26,
          HomeTeamID: 12,
          RescheduledGameID: null,
          StadiumID: 51,
          Channel: 'CSP, FSSE',
          Inning: 9,
          InningHalf: 'T',
          AwayTeamRuns: 6,
          HomeTeamRuns: 7,
          AwayTeamHits: 10,
          HomeTeamHits: 9,
          AwayTeamErrors: 1,
          HomeTeamErrors: 0,
          WinningPitcherID: 10006571,
          LosingPitcherID: 10000466,
          SavingPitcherID: 10000939,
          Attendance: null,
          AwayTeamProbablePitcherID: 10000466,
          HomeTeamProbablePitcherID: 10006571,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10000466,
          HomeTeamStartingPitcherID: 10006571,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: 1.5,
          OverUnder: 8.5,
          AwayTeamMoneyLine: -120,
          HomeTeamMoneyLine: 100,
          ForecastTempLow: 64,
          ForecastTempHigh: 71,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 64,
          ForecastWindSpeed: 3,
          ForecastWindDirection: 261,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Mike Foltynewicz',
          HomeTeamStartingPitcher: 'Nick Pivetta',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Nick Pivetta',
          LosingPitcher: 'Mike Foltynewicz',
          SavingPitcher: 'Héctor Neris',
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049127,
          GlobalAwayTeamID: 10000026,
          GlobalHomeTeamID: 10000012,
          PointSpreadAwayTeamMoneyLine: 145,
          PointSpreadHomeTeamMoneyLine: -165,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:57',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312424, GameID: 49127, InningNumber: 1, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312425, GameID: 49127, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312426, GameID: 49127, InningNumber: 3, AwayTeamRuns: 0, HomeTeamRuns: 4 },
            { InningID: 312427, GameID: 49127, InningNumber: 4, AwayTeamRuns: 0, HomeTeamRuns: 1 },
            { InningID: 312428, GameID: 49127, InningNumber: 5, AwayTeamRuns: 1, HomeTeamRuns: 0 },
            { InningID: 312429, GameID: 49127, InningNumber: 6, AwayTeamRuns: 0, HomeTeamRuns: 1 },
            { InningID: 312430, GameID: 49127, InningNumber: 7, AwayTeamRuns: 3, HomeTeamRuns: 1 },
            { InningID: 312431, GameID: 49127, InningNumber: 8, AwayTeamRuns: 1, HomeTeamRuns: 0 },
            {
              InningID: 312432,
              GameID: 49127,
              InningNumber: 9,
              AwayTeamRuns: 1,
              HomeTeamRuns: null,
            },
          ],
        },
        {
          GameID: 49119,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T19:05:00',
          AwayTeam: 'KC',
          HomeTeam: 'BAL',
          AwayTeamID: 5,
          HomeTeamID: 19,
          RescheduledGameID: null,
          StadiumID: 22,
          Channel: 'MASN2, FSKC',
          Inning: 9,
          InningHalf: 'B',
          AwayTeamRuns: 1,
          HomeTeamRuns: 2,
          AwayTeamHits: 5,
          HomeTeamHits: 10,
          AwayTeamErrors: 0,
          HomeTeamErrors: 1,
          WinningPitcherID: 10000094,
          LosingPitcherID: 10000429,
          SavingPitcherID: null,
          Attendance: null,
          AwayTeamProbablePitcherID: 10000506,
          HomeTeamProbablePitcherID: 10000104,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10000506,
          HomeTeamStartingPitcherID: 10000104,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: 1.5,
          OverUnder: 9.5,
          AwayTeamMoneyLine: -115,
          HomeTeamMoneyLine: -105,
          ForecastTempLow: 69,
          ForecastTempHigh: 75,
          ForecastDescription: 'Broken Clouds',
          ForecastWindChill: 69,
          ForecastWindSpeed: 1,
          ForecastWindDirection: 222,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Danny Duffy',
          HomeTeamStartingPitcher: 'Ubaldo Jiménez',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Zack Britton',
          LosingPitcher: 'Joakim Soria',
          SavingPitcher: null,
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049119,
          GlobalAwayTeamID: 10000005,
          GlobalHomeTeamID: 10000019,
          PointSpreadAwayTeamMoneyLine: 145,
          PointSpreadHomeTeamMoneyLine: -165,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:16',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312433, GameID: 49119, InningNumber: 1, AwayTeamRuns: 1, HomeTeamRuns: 0 },
            { InningID: 312438, GameID: 49119, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312442, GameID: 49119, InningNumber: 3, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312447, GameID: 49119, InningNumber: 4, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312453, GameID: 49119, InningNumber: 5, AwayTeamRuns: 0, HomeTeamRuns: 1 },
            { InningID: 312461, GameID: 49119, InningNumber: 6, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312466, GameID: 49119, InningNumber: 7, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312473, GameID: 49119, InningNumber: 8, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312475, GameID: 49119, InningNumber: 9, AwayTeamRuns: 0, HomeTeamRuns: 1 },
          ],
        },
        {
          GameID: 49122,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T19:05:00',
          AwayTeam: 'DET',
          HomeTeam: 'NYY',
          AwayTeamID: 17,
          HomeTeamID: 29,
          RescheduledGameID: null,
          StadiumID: 35,
          Channel: 'YES, FSD',
          Inning: 9,
          InningHalf: 'T',
          AwayTeamRuns: 3,
          HomeTeamRuns: 7,
          AwayTeamHits: 9,
          HomeTeamHits: 7,
          AwayTeamErrors: 1,
          HomeTeamErrors: 2,
          WinningPitcherID: 10002077,
          LosingPitcherID: 10005327,
          SavingPitcherID: 10000278,
          Attendance: null,
          AwayTeamProbablePitcherID: 10005327,
          HomeTeamProbablePitcherID: 10002077,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10005327,
          HomeTeamStartingPitcherID: 10002077,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: -1.5,
          OverUnder: 8.5,
          AwayTeamMoneyLine: 190,
          HomeTeamMoneyLine: -220,
          ForecastTempLow: 71,
          ForecastTempHigh: 74,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 71,
          ForecastWindSpeed: 7,
          ForecastWindDirection: 183,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Michael Fulmer',
          HomeTeamStartingPitcher: 'Luis Severino',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Luis Severino',
          LosingPitcher: 'Michael Fulmer',
          SavingPitcher: 'Aroldis Chapman',
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049122,
          GlobalAwayTeamID: 10000017,
          GlobalHomeTeamID: 10000029,
          PointSpreadAwayTeamMoneyLine: -105,
          PointSpreadHomeTeamMoneyLine: -115,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:28',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312434, GameID: 49122, InningNumber: 1, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312440, GameID: 49122, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312443, GameID: 49122, InningNumber: 3, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312446, GameID: 49122, InningNumber: 4, AwayTeamRuns: 1, HomeTeamRuns: 4 },
            { InningID: 312460, GameID: 49122, InningNumber: 5, AwayTeamRuns: 0, HomeTeamRuns: 1 },
            { InningID: 312469, GameID: 49122, InningNumber: 6, AwayTeamRuns: 1, HomeTeamRuns: 0 },
            { InningID: 312478, GameID: 49122, InningNumber: 7, AwayTeamRuns: 0, HomeTeamRuns: 2 },
            { InningID: 312484, GameID: 49122, InningNumber: 8, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            {
              InningID: 312488,
              GameID: 49122,
              InningNumber: 9,
              AwayTeamRuns: 1,
              HomeTeamRuns: null,
            },
          ],
        },
        {
          GameID: 49120,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T19:08:00',
          AwayTeam: 'CLE',
          HomeTeam: 'BOS',
          AwayTeamID: 10,
          HomeTeamID: 25,
          RescheduledGameID: null,
          StadiumID: 50,
          Channel: 'NESN, STO, ESPN',
          Inning: 9,
          InningHalf: 'T',
          AwayTeamRuns: 2,
          HomeTeamRuns: 6,
          AwayTeamHits: 7,
          HomeTeamHits: 13,
          AwayTeamErrors: 1,
          HomeTeamErrors: 0,
          WinningPitcherID: 10001335,
          LosingPitcherID: 10005311,
          SavingPitcherID: null,
          Attendance: null,
          AwayTeamProbablePitcherID: 10005311,
          HomeTeamProbablePitcherID: 10001335,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10005311,
          HomeTeamStartingPitcherID: 10001335,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: 1.5,
          OverUnder: 10,
          AwayTeamMoneyLine: -134,
          HomeTeamMoneyLine: 114,
          ForecastTempLow: 67,
          ForecastTempHigh: 67,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 67,
          ForecastWindSpeed: 8,
          ForecastWindDirection: 183,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Mike Clevinger',
          HomeTeamStartingPitcher: 'Doug Fister',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Doug Fister',
          LosingPitcher: 'Mike Clevinger',
          SavingPitcher: null,
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049120,
          GlobalAwayTeamID: 10000010,
          GlobalHomeTeamID: 10000025,
          PointSpreadAwayTeamMoneyLine: 120,
          PointSpreadHomeTeamMoneyLine: -140,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:19',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312435, GameID: 49120, InningNumber: 1, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312437, GameID: 49120, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 3 },
            { InningID: 312444, GameID: 49120, InningNumber: 3, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312450, GameID: 49120, InningNumber: 4, AwayTeamRuns: 0, HomeTeamRuns: 2 },
            { InningID: 312458, GameID: 49120, InningNumber: 5, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312464, GameID: 49120, InningNumber: 6, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312472, GameID: 49120, InningNumber: 7, AwayTeamRuns: 0, HomeTeamRuns: 1 },
            { InningID: 312479, GameID: 49120, InningNumber: 8, AwayTeamRuns: 2, HomeTeamRuns: 0 },
            {
              InningID: 312483,
              GameID: 49120,
              InningNumber: 9,
              AwayTeamRuns: 0,
              HomeTeamRuns: null,
            },
          ],
        },
        {
          GameID: 49126,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T19:10:00',
          AwayTeam: 'WSH',
          HomeTeam: 'MIA',
          AwayTeamID: 35,
          HomeTeamID: 22,
          RescheduledGameID: null,
          StadiumID: 57,
          Channel: 'MASN, FSFL',
          Inning: 9,
          InningHalf: 'B',
          AwayTeamRuns: 1,
          HomeTeamRuns: 0,
          AwayTeamHits: 3,
          HomeTeamHits: 2,
          AwayTeamErrors: 0,
          HomeTeamErrors: 1,
          WinningPitcherID: 10001337,
          LosingPitcherID: 10003284,
          SavingPitcherID: 10000884,
          Attendance: null,
          AwayTeamProbablePitcherID: 10001337,
          HomeTeamProbablePitcherID: 10003284,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10001337,
          HomeTeamStartingPitcherID: 10003284,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: 1.5,
          OverUnder: 9,
          AwayTeamMoneyLine: -138,
          HomeTeamMoneyLine: 118,
          ForecastTempLow: 77,
          ForecastTempHigh: 80,
          ForecastDescription: 'Broken Clouds',
          ForecastWindChill: 80,
          ForecastWindSpeed: 8,
          ForecastWindDirection: 174,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Gio González',
          HomeTeamStartingPitcher: 'José Ureña',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Gio González',
          LosingPitcher: 'José Ureña',
          SavingPitcher: 'Sean Doolittle',
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049126,
          GlobalAwayTeamID: 10000035,
          GlobalHomeTeamID: 10000022,
          PointSpreadAwayTeamMoneyLine: 115,
          PointSpreadHomeTeamMoneyLine: -135,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:48',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312436, GameID: 49126, InningNumber: 1, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312439, GameID: 49126, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312441, GameID: 49126, InningNumber: 3, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312445, GameID: 49126, InningNumber: 4, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312452, GameID: 49126, InningNumber: 5, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312454, GameID: 49126, InningNumber: 6, AwayTeamRuns: 1, HomeTeamRuns: 0 },
            { InningID: 312459, GameID: 49126, InningNumber: 7, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312465, GameID: 49126, InningNumber: 8, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312470, GameID: 49126, InningNumber: 9, AwayTeamRuns: 0, HomeTeamRuns: 0 },
          ],
        },
        {
          GameID: 49124,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T20:05:00',
          AwayTeam: 'SEA',
          HomeTeam: 'TEX',
          AwayTeamID: 13,
          HomeTeamID: 28,
          RescheduledGameID: null,
          StadiumID: 21,
          Channel: 'FSSW, RTNW',
          Inning: 9,
          InningHalf: 'B',
          AwayTeamRuns: 6,
          HomeTeamRuns: 4,
          AwayTeamHits: 8,
          HomeTeamHits: 6,
          AwayTeamErrors: 1,
          HomeTeamErrors: 4,
          WinningPitcherID: 10000670,
          LosingPitcherID: 10001232,
          SavingPitcherID: 10005753,
          Attendance: null,
          AwayTeamProbablePitcherID: 10001065,
          HomeTeamProbablePitcherID: 10000931,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10001065,
          HomeTeamStartingPitcherID: 10000931,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: -1.5,
          OverUnder: 10.5,
          AwayTeamMoneyLine: -110,
          HomeTeamMoneyLine: -110,
          ForecastTempLow: 76,
          ForecastTempHigh: 81,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 76,
          ForecastWindSpeed: 8,
          ForecastWindDirection: 79,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Félix Hernández',
          HomeTeamStartingPitcher: 'Cole Hamels',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'David Phelps',
          LosingPitcher: 'Alex Claudio',
          SavingPitcher: 'Edwin Díaz',
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049124,
          GlobalAwayTeamID: 10000013,
          GlobalHomeTeamID: 10000028,
          PointSpreadAwayTeamMoneyLine: -210,
          PointSpreadHomeTeamMoneyLine: 175,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:39',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312448, GameID: 49124, InningNumber: 1, AwayTeamRuns: 0, HomeTeamRuns: 2 },
            { InningID: 312456, GameID: 49124, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 2 },
            { InningID: 312463, GameID: 49124, InningNumber: 3, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312471, GameID: 49124, InningNumber: 4, AwayTeamRuns: 3, HomeTeamRuns: 0 },
            { InningID: 312477, GameID: 49124, InningNumber: 5, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312482, GameID: 49124, InningNumber: 6, AwayTeamRuns: 1, HomeTeamRuns: 0 },
            { InningID: 312489, GameID: 49124, InningNumber: 7, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312496, GameID: 49124, InningNumber: 8, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312497, GameID: 49124, InningNumber: 9, AwayTeamRuns: 2, HomeTeamRuns: 0 },
          ],
        },
        {
          GameID: 49121,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T20:10:00',
          AwayTeam: 'TOR',
          HomeTeam: 'CHW',
          AwayTeamID: 3,
          HomeTeamID: 16,
          RescheduledGameID: null,
          StadiumID: 25,
          Channel: 'CSCh, RSN',
          Inning: 9,
          InningHalf: 'B',
          AwayTeamRuns: 6,
          HomeTeamRuns: 7,
          AwayTeamHits: 9,
          HomeTeamHits: 10,
          AwayTeamErrors: 1,
          HomeTeamErrors: 0,
          WinningPitcherID: 10001922,
          LosingPitcherID: 10001957,
          SavingPitcherID: null,
          Attendance: null,
          AwayTeamProbablePitcherID: 10001290,
          HomeTeamProbablePitcherID: 10000519,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10001290,
          HomeTeamStartingPitcherID: 10000519,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: 1.5,
          OverUnder: 10.5,
          AwayTeamMoneyLine: -192,
          HomeTeamMoneyLine: 166,
          ForecastTempLow: 70,
          ForecastTempHigh: 74,
          ForecastDescription: 'Scattered Clouds',
          ForecastWindChill: 70,
          ForecastWindSpeed: 6,
          ForecastWindDirection: 123,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Marco Estrada',
          HomeTeamStartingPitcher: 'James Shields',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Chris Beck',
          LosingPitcher: 'Roberto Osuna',
          SavingPitcher: null,
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049121,
          GlobalAwayTeamID: 10000003,
          GlobalHomeTeamID: 10000016,
          PointSpreadAwayTeamMoneyLine: -125,
          PointSpreadHomeTeamMoneyLine: 105,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:24',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312451, GameID: 49121, InningNumber: 1, AwayTeamRuns: 1, HomeTeamRuns: 0 },
            { InningID: 312455, GameID: 49121, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312462, GameID: 49121, InningNumber: 3, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312467, GameID: 49121, InningNumber: 4, AwayTeamRuns: 2, HomeTeamRuns: 0 },
            { InningID: 312474, GameID: 49121, InningNumber: 5, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312480, GameID: 49121, InningNumber: 6, AwayTeamRuns: 3, HomeTeamRuns: 0 },
            { InningID: 312485, GameID: 49121, InningNumber: 7, AwayTeamRuns: 0, HomeTeamRuns: 1 },
            { InningID: 312491, GameID: 49121, InningNumber: 8, AwayTeamRuns: 0, HomeTeamRuns: 4 },
            { InningID: 312494, GameID: 49121, InningNumber: 9, AwayTeamRuns: 0, HomeTeamRuns: 2 },
          ],
        },
        {
          GameID: 49125,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T20:10:00',
          AwayTeam: 'TB',
          HomeTeam: 'HOU',
          AwayTeamID: 11,
          HomeTeamID: 30,
          RescheduledGameID: null,
          StadiumID: 63,
          Channel: 'SUN',
          Inning: 9,
          InningHalf: 'T',
          AwayTeamRuns: 7,
          HomeTeamRuns: 14,
          AwayTeamHits: 7,
          HomeTeamHits: 17,
          AwayTeamErrors: 1,
          HomeTeamErrors: 0,
          WinningPitcherID: 10000981,
          LosingPitcherID: 10001191,
          SavingPitcherID: null,
          Attendance: null,
          AwayTeamProbablePitcherID: 10001191,
          HomeTeamProbablePitcherID: 10000981,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10001191,
          HomeTeamStartingPitcherID: 10000981,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: -1.5,
          OverUnder: 9,
          AwayTeamMoneyLine: 133,
          HomeTeamMoneyLine: -153,
          ForecastTempLow: 78,
          ForecastTempHigh: 84,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 78,
          ForecastWindSpeed: 6,
          ForecastWindDirection: 109,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Alex Cobb',
          HomeTeamStartingPitcher: 'Charlie Morton',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Charlie Morton',
          LosingPitcher: 'Alex Cobb',
          SavingPitcher: null,
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049125,
          GlobalAwayTeamID: 10000011,
          GlobalHomeTeamID: 10000030,
          PointSpreadAwayTeamMoneyLine: -160,
          PointSpreadHomeTeamMoneyLine: 140,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:44',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312449, GameID: 49125, InningNumber: 1, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312457, GameID: 49125, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 3 },
            { InningID: 312468, GameID: 49125, InningNumber: 3, AwayTeamRuns: 2, HomeTeamRuns: 5 },
            { InningID: 312476, GameID: 49125, InningNumber: 4, AwayTeamRuns: 0, HomeTeamRuns: 2 },
            { InningID: 312481, GameID: 49125, InningNumber: 5, AwayTeamRuns: 0, HomeTeamRuns: 1 },
            { InningID: 312486, GameID: 49125, InningNumber: 6, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312490, GameID: 49125, InningNumber: 7, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312493, GameID: 49125, InningNumber: 8, AwayTeamRuns: 4, HomeTeamRuns: 3 },
            {
              InningID: 312499,
              GameID: 49125,
              InningNumber: 9,
              AwayTeamRuns: 1,
              HomeTeamRuns: null,
            },
          ],
        },
        {
          GameID: 49123,
          Season: 2017,
          SeasonType: 1,
          Status: 'Final',
          Day: '2017-07-31T00:00:00',
          DateTime: '2017-07-31T22:05:00',
          AwayTeam: 'SF',
          HomeTeam: 'OAK',
          AwayTeamID: 15,
          HomeTeamID: 24,
          RescheduledGameID: null,
          StadiumID: 23,
          Channel: 'CSCA, CSBA',
          Inning: 9,
          InningHalf: 'T',
          AwayTeamRuns: 5,
          HomeTeamRuns: 8,
          AwayTeamHits: 11,
          HomeTeamHits: 12,
          AwayTeamErrors: 0,
          HomeTeamErrors: 0,
          WinningPitcherID: 10005560,
          LosingPitcherID: 10004781,
          SavingPitcherID: 10001352,
          Attendance: null,
          AwayTeamProbablePitcherID: 10001106,
          HomeTeamProbablePitcherID: 10005560,
          Outs: null,
          Balls: null,
          Strikes: null,
          CurrentPitcherID: null,
          CurrentHitterID: null,
          AwayTeamStartingPitcherID: 10001106,
          HomeTeamStartingPitcherID: 10005560,
          CurrentPitchingTeamID: null,
          CurrentHittingTeamID: null,
          PointSpread: -1.5,
          OverUnder: 9.5,
          AwayTeamMoneyLine: 136,
          HomeTeamMoneyLine: -156,
          ForecastTempLow: 62,
          ForecastTempHigh: 66,
          ForecastDescription: 'Clear Sky',
          ForecastWindChill: 66,
          ForecastWindSpeed: 4,
          ForecastWindDirection: 245,
          RescheduledFromGameID: null,
          RunnerOnFirst: null,
          RunnerOnSecond: null,
          RunnerOnThird: null,
          AwayTeamStartingPitcher: 'Matt Cain',
          HomeTeamStartingPitcher: 'Paul Blackburn',
          CurrentPitcher: null,
          CurrentHitter: null,
          WinningPitcher: 'Paul Blackburn',
          LosingPitcher: 'Josh Osich',
          SavingPitcher: 'Blake Treinen',
          DueUpHitterID1: null,
          DueUpHitterID2: null,
          DueUpHitterID3: null,
          GlobalGameID: 10049123,
          GlobalAwayTeamID: 10000015,
          GlobalHomeTeamID: 10000024,
          PointSpreadAwayTeamMoneyLine: -145,
          PointSpreadHomeTeamMoneyLine: 125,
          LastPlay: null,
          IsClosed: true,
          Updated: '2021-09-21T13:35:44',
          GameEndDateTime: '2018-07-30T22:50:33',
          HomeRotationNumber: null,
          AwayRotationNumber: null,
          NeutralVenue: null,
          InningDescription: null,
          OverPayout: null,
          UnderPayout: null,
          SeriesInfo: null,
          Innings: [
            { InningID: 312487, GameID: 49123, InningNumber: 1, AwayTeamRuns: 1, HomeTeamRuns: 2 },
            { InningID: 312492, GameID: 49123, InningNumber: 2, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312495, GameID: 49123, InningNumber: 3, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312498, GameID: 49123, InningNumber: 4, AwayTeamRuns: 2, HomeTeamRuns: 0 },
            { InningID: 312500, GameID: 49123, InningNumber: 5, AwayTeamRuns: 0, HomeTeamRuns: 0 },
            { InningID: 312501, GameID: 49123, InningNumber: 6, AwayTeamRuns: 0, HomeTeamRuns: 4 },
            { InningID: 312502, GameID: 49123, InningNumber: 7, AwayTeamRuns: 2, HomeTeamRuns: 0 },
            { InningID: 312503, GameID: 49123, InningNumber: 8, AwayTeamRuns: 0, HomeTeamRuns: 2 },
            {
              InningID: 312504,
              GameID: 49123,
              InningNumber: 9,
              AwayTeamRuns: 0,
              HomeTeamRuns: null,
            },
          ],
        },
      ],
      [
        'Connection',
        'close',
        'Content-Length',
        '23257',
        'Content-Type',
        'application/json; charset=utf-8',
        'Last-Modified',
        'Wed, 03 Nov 2021 18:40:00 GMT',
        'X-AspNet-Version',
        '4.0.30319',
        'Cache-Control',
        'must-revalidate, max-age=4',
        'Via',
        '1.1 varnish, 1.1 varnish',
        'Fastly-Restarts',
        '1',
        'Accept-Ranges',
        'bytes',
        'Date',
        'Wed, 03 Nov 2021 18:48:16 GMT',
        'Age',
        '495',
        'X-Served-By',
        'cache-pwk4950-PWK, cache-sea4456-SEA',
        'X-Cache',
        'MISS, HIT',
        'X-Cache-Hits',
        '0, 2',
        'X-Timer',
        'S1635965297.790541,VS0,VE0',
        'Vary',
        'x-subtier, Accept-Encoding',
        'Access-Control-Allow-Origin',
        '*',
      ],
    )
}
