const HTTP_ERROR_NOT_IMPLEMENTED = 501

const HTTP_ERROR_UNSUPPORTED_MEDIA_TYPE = 415
const HTTP_ERROR_UNSUPPORTED_MEDIA_TYPE_MESSAGE = 'Only application/json media type is supported.'

module.exports = {
  HTTP_ERROR_NOT_IMPLEMENTED,
  HTTP_ERROR_UNSUPPORTED_MEDIA_TYPE,
  HTTP_ERROR_UNSUPPORTED_MEDIA_TYPE_MESSAGE,
}
