export { endpoint as address } from './address'
export { endpoint as bedrockBTC } from './bedrockBTC'
export { endpoint as coinbaseBTC } from './coinbaseCBBTC'
export { endpoint as multichainAddress } from './multichainAddress'
export { endpoint as openedenAddress } from './openEdenUSDOAddress'
export { endpoint as solvBTC } from './solvBTC'
export { endpoint as virtune } from './virtune'
export { endpoint as zeusBtcAddress } from './zeusBTC'
