name: Setup
description: Runs basic commands to bootstrap yarn and install dependencies
inputs:
  check-cache:
    description: Passes the --check-cache flag to yarn install for verification jobs
    required: false
    default: 'false'
  skip-setup:
    description: Skips the "yarn setup" step when not required
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Check NPM_AUTH_TOKEN is defined # .yarnrc.yml requires NPM_AUTH_TOKEN to be set as an env var specifically
      if: ${{ env.NPM_AUTH_TOKEN  == '' }}
      run: exit 1
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install yarn
      run: npm i -g yarn
      shell: bash
    - run: |
        yarn config set npmRegistryServer https://registry.npmjs.org/
        yarn config set npmAlwaysAuth true
        yarn config set npmAuthToken ${{ env.NPM_AUTH_TOKEN}}
      shell: bash
    - run: yarn prettier --write .yarnrc.yml #`yarn config set` strips the newline from .yarnrc.yml, so restore it
      shell: bash
    - name: yarn install
      run: |
        if [ "${{ inputs.check-cache }}" = "true" ]; then
          yarn install --immutable --check-cache
        else 
          yarn install --immutable
        fi
      shell: bash
    - name: yarn setup
      run: yarn setup
      shell: bash
      if: ${{ inputs.skip-setup != 'true' }} # Not all jobs, like building gha matrices, require setup
