name: Setup
description: Runs basic commands to bootstrap yarn and install dependencies
inputs:
  check-cache:
    description: Passes the --check-cache flag to yarn install for verification jobs
    required: false
    default: 'false'
  skip-setup:
    description: Skips the "yarn setup" step when not required
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install yarn
      run: npm i -g yarn
      shell: bash
    - name: yarn install
      run: |
        if [ "${{ inputs.check-cache }}" = "true" ]; then
          yarn install --immutable --check-cache
        else 
          yarn install --immutable
        fi
      shell: bash
    - name: Restore TS built files if present
      id: restore-ts-build
      uses: actions/cache/restore@v3
      if: ${{ inputs.skip-setup != 'true' }} # Not all jobs, like building gha matrices, require setup
      with:
        key: tsbuild-${{ github.sha }}
    - name: yarn setup
      if: steps.restore-ts-build.cache-hit != 'true'
      run: yarn setup
      shell: bash
    - name: Cache built files
      uses: actions/cache/save@v3
      with:
        key: tsbuild-${{ github.sha }}
        path: |
          ./packages/**/tsconfig.tsbuildinfo
          ./packages/**/dist/
