#!/usr/bin/env bash

set -e

# This script will read a file, parse it as multi line json,
# and set it as `matrix` output for GitHub CI job step

content=`cat $1`
# the following lines are only required for multi line json
content="${content//'%'/'%25'}"
content="${content//$'\n'/'%0A'}"
content="${content//$'\r'/'%0D'}"
# end of optional handling for multi line json
echo "::set-output name=matrix::$content"
