packageExtensions:
  '@ethereumjs/vm@*':
    dependencies:
      rlp: '*'
  '@renproject/chains@*':
    dependencies:
      send-crypto: '*'
  '@renproject/utils@*':
    dependencies:
      web3-utils: '*'
  '@renproject/rpc@*':
    dependencies:
      bn.js: '*'
  '@renproject/ren@*':
    dependencies:
      bs58: '*'
  web3-eth@*:
    dependencies:
      bs58: '*'
  'follow-redirects@*':
    dependencies:
      debug: '*'
  '@terra-money/terra.js@*':
    dependencies:
      long: '*'
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.0.0.cjs
nodeLinker: 'pnp'
