plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-2.4.1.cjs

packageExtensions:
  '@ethereumjs/vm@*':
    dependencies:
      'rlp': '*'
  '@renproject/chains@*':
    dependencies:
      'send-crypto': '*'
  '@renproject/utils@*':
    dependencies:
      'web3-utils': '*'
  'web3-eth@*':
    dependencies:
      'lodash': '*'
