compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  '@aws-sdk/credential-provider-ini@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
  '@aws-sdk/credential-provider-web-identity@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
  '@aws-sdk/token-providers@*':
    dependencies:
      '@aws-sdk/client-sso-oidc': '*'
  '@ethereumjs/vm@*':
    dependencies:
      rlp: '*'
  '@harmony-js/account@*':
    dependencies:
      tslib: '*'
  '@harmony-js/contract@*':
    dependencies:
      tslib: '*'
  '@harmony-js/core@*':
    dependencies:
      tslib: '*'
  '@harmony-js/crypto@*':
    dependencies:
      tslib: '*'
  '@harmony-js/network@*':
    dependencies:
      tslib: '*'
  '@harmony-js/staking@*':
    dependencies:
      tslib: '*'
  '@harmony-js/transaction@*':
    dependencies:
      tslib: '*'
  '@harmony-js/utils@*':
    dependencies:
      tslib: '*'
  '@renproject/chains@*':
    dependencies:
      send-crypto: '*'
  '@renproject/ren@*':
    dependencies:
      bs58: '*'
  '@renproject/rpc@*':
    dependencies:
      bn.js: '*'
  '@renproject/utils@*':
    dependencies:
      web3-utils: '*'
  '@terra-money/terra.js@*':
    dependencies:
      long: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  web3-eth@*:
    dependencies:
      bs58: '*'

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-4.5.1.cjs
