plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.1.cjs

packageExtensions:
  'mocha@*':
    dependencies:
      'ts-node': '*'
      'lodash': '*'
  '@harmony-js/core@*':
    dependencies:
      'tslib': '*'
  '@harmony-js/crypto@*':
    dependencies:
      'tslib': '*'
  '@harmony-js/utils@*':
    dependencies:
      'tslib': '*'
  '@harmony-js/network@*':
    dependencies:
      'tslib': '*'
  '@harmony-js/transaction@*':
    dependencies:
      'tslib': '*'
  '@harmony-js/staking@*':
    dependencies:
      'tslib': '*'
  '@harmony-js/contract@*':
    dependencies:
      'tslib': '*'
  '@harmony-js/account@*':
    dependencies:
      'tslib': '*'
