FROM node:12 as builder
ARG adapter
WORKDIR /home/node/app

COPY . .
RUN make deps
RUN make build-2-step

FROM node:12-alpine
ARG adapter
EXPOSE 8080
WORKDIR /home/node/app

COPY --from=builder /home/node/app/2-step/$adapter/dist ./
COPY --from=builder /home/node/app/2-step/$adapter/package.json ./

CMD ["yarn", "server"]
