FROM node:12 as builder
ARG adapter
ARG check
WORKDIR /home/node/app

COPY package.json yarn.lock Makefile ./
COPY bootstrap/package.json bootstrap/package.json
RUN make deps

COPY bootstrap bootstrap
COPY $adapter $adapter
COPY market-closure market-closure
COPY market-closure/$check market-closure/$check
RUN make build-market-closure

FROM node:12-alpine
ARG check
WORKDIR /home/node/app

COPY --from=builder /home/node/app/market-closure/$check/dist ./
COPY --from=builder /home/node/app/market-closure/$check/package.json ./

CMD ["yarn", "server"]
