FROM node:12 as builder
ARG adapter
ARG check
WORKDIR /home/node/app

COPY package.json yarn.lock Makefile ./
COPY external-adapter/package.json external-adapter/package.json
COPY bootstrap/package.json bootstrap/package.json
RUN make deps

COPY typings typings
COPY bootstrap bootstrap
COPY external-adapter external-adapter
COPY $adapter $adapter
COPY market-closure market-closure
COPY market-closure/$check market-closure/$check
COPY helpers helpers
RUN make build-market-closure

FROM node:12-alpine
ARG check
EXPOSE 8080
WORKDIR /home/node/app

COPY --from=builder /home/node/app/market-closure/$check/dist ./
COPY --from=builder /home/node/app/market-closure/$check/package.json ./

CMD ["yarn", "server"]
