[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:js-adapter]
command=yarn server
directory=/home/node/app
autostart=true
autorestart=unexpected
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5
environment=CACHE_TYPE=redis,CACHE_REDIS_HOST=localhost,EA_PORT="8070",EA_HOST="127.0.0.1",METRICS_ENABLED=true,METRICS_PORT=9081

[program:go-adapter]
command=/usr/local/bin/streams-adapter
autostart=true
autorestart=unexpected
exitcodes=0
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=0
