import nock from 'nock'

const year = new Date().getFullYear()

export const mockDataProviderResponses = (): nock.Scope =>
  nock('https://apps.bea.gov/api/', {
    encodedQueryParams: true,
  })
    .persist()
    .get('/data')
    .query({
      userID: 'fake_api',
      DataSetName: 'NIPA',
      TableName: 'T20804',
      ResultFormat: 'json',
      method: 'getData',
      Frequency: 'M',
      year: `${year},${year - 1}`,
    })
    .reply(
      200,
      () => ({
        BEAAPI: {
          Results: {
            Data: [
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M10',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '111.775',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2021M07',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '115.849',
                NoteRef: 'T20804',
              },

              {
                TableName: 'T20804',
                SeriesCode: 'DGDSRG',
                LineNumber: '2',
                LineDescription: 'Goods',
                TimePeriod: '2020M01',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '94.989',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2021M08',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '116.314',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M01',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '111.002',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M03',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '110.802',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M02',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '111.071',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M04',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '110.213',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M06',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '110.918',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M07',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '111.221',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M05',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '110.385',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M08',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '111.563',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M09',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '111.736',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M12',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '112.220',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2021M01',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '112.570',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2021M02',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '112.878',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2021M03',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '113.518',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2021M05',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '114.767',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2021M04',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '114.161',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2021M06',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '115.388',
                NoteRef: 'T20804',
              },
              {
                TableName: 'T20804',
                SeriesCode: 'DPCERG',
                LineNumber: '1',
                LineDescription: 'Personal consumption expenditures (PCE)',
                TimePeriod: '2020M11',
                METRIC_NAME: 'Fisher Price Index',
                CL_UNIT: 'Level',
                UNIT_MULT: '0',
                DataValue: '111.790',
                NoteRef: 'T20804',
              },
            ],
            Notes: [],
          },
        },
      }),
      [
        'X-Powered-By',
        'Express',
        'Content-Type',
        'application/json; charset=utf-8',
        'Content-Length',
        '714',
        'ETag',
        'W/"4c-80HqZxTKkxT2QbzJJxLmlKoGX1c"',
        'Date',
        'Mon, 20 Sep 2021 14:30:57 GMT',
        'Connection',
        'close',
      ],
    )
