import nock from 'nock'

export const mockResponseWithNoRaces = (apikey) => {
  nock('https://api.ap.org/v2', { encodedQueryParams: true })
    .get('/elections/2021-06-08')
    .query({
      statePostal: 'VA',
      officeID: 'A',
      level: 'state',
      raceTypeID: 'D',
      format: 'json',
      winner: 'X',
      resultsType: 'l',
      apikey,
    })
    .reply(
      200,
      {
        electionDate: '2021-06-08',
        timestamp: '2021-10-12T15:41:05.383Z',
        races: [],
        nextrequest:
          'https://api.ap.org/v2/elections/2021-06-08?format=json&level=state&officeid=A&racetypeid=D&resultstype=l&statepostal=VA&winner=X&minDateTime=2021-06-09T20%3a35%3a40.840Z',
      },
      [
        'Content-Type',
        'application/json',
        'Content-Length',
        '929',
        'Connection',
        'close',
        'Date',
        'Tue, 12 Oct 2021 15:41:05 GMT',
        'x-amzn-RequestId',
        'd38f92b4-b1eb-4941-8522-dd732217f233',
        'Last-Modified',
        'Wed, 09 Jun 2021 20:35:40 GMT',
        'x-electionsapi-Q-minute-secondsLeft',
        '56',
        'x-electionsapi-Q-minute-used',
        '1',
        'x-electionsapi-Q-minute-allowed',
        '10',
        'x-electionsapi-Q-minute-available',
        '9',
        'x-amzn-Remapped-Connection',
        'keep-alive',
        'x-electionsapi-Q-minute-name',
        'elections',
        'x-amz-apigw-id',
        'HGfmvHv-IAMFdfw=',
        'Cache-Control',
        'private',
        'ETag',
        '"c361e0ea77eceb267b3c2233c0a376e0-20210609203540840-JSON"',
        'x-nancygzip',
        'noreq',
        'x-electionsapi-sid',
        'd38f92b4-b1eb-4941-8522-dd732217f233',
        'X-Amzn-Trace-Id',
        'Root=1-6165ac91-4b23e59d2657db775f2627a8',
        'x-amzn-Remapped-date',
        'Tue, 12 Oct 2021 15:41:04 GMT',
        'X-Cache',
        'Miss from cloudfront',
        'Via',
        '1.1 4f87745990545c1ac0195c157e1668f8.cloudfront.net (CloudFront)',
        'X-Amz-Cf-Pop',
        'HIO50-C1',
        'X-Amz-Cf-Id',
        'zkTR6tAkwmYZBYZXIx9Ix4dMC36_CikTNkqLYuSBn-sJW7mDAgnVuw==',
      ],
    )
}

export const mockResponseWithMultipleRaces = (apikey) => {
  nock('https://api.ap.org/v2', { encodedQueryParams: true })
    .get('/elections/2021-06-08')
    .query({
      statePostal: 'VA',
      officeID: 'A',
      level: 'state',
      raceTypeID: 'D',
      format: 'json',
      winner: 'X',
      resultsType: 'l',
      apikey,
    })
    .reply(
      200,
      {
        electionDate: '2021-06-08',
        timestamp: '2021-10-12T15:41:05.383Z',
        races: [
          {
            test: false,
            resultsType: 'live',
            raceID: '0',
            raceType: 'General',
            raceTypeID: 'G',
            officeID: 'P',
            officeName: 'President',
            reportingUnits: [
              {
                statePostal: 'US',
                stateName: 'United States',
                level: 'national',
                lastUpdated: '2021-06-09T20:35:40.840Z',
                precinctsReporting: 2584,
                precinctsTotal: 2584,
                precinctsReportingPct: 100,
                candidates: [
                  {
                    first: 'Donald',
                    last: 'Trump',
                    party: 'Rep',
                    incumbent: true,
                    candidateID: '51896',
                    polID: '0',
                    ballotOrder: 1,
                    polNum: '49353',
                    voteCount: 280076,
                  },
                  {
                    first: 'Joe',
                    last: 'Biden',
                    party: 'Dem',
                    candidateID: '52107',
                    polID: '0',
                    ballotOrder: 2,
                    polNum: '49500',
                    voteCount: 271187,
                    winner: 'X',
                  },
                ],
              },
              {
                statePostal: 'VA',
                stateName: 'Virginia',
                level: 'state',
                lastUpdated: '2021-06-09T20:35:40.840Z',
                precinctsReporting: 2584,
                precinctsTotal: 2584,
                precinctsReportingPct: 100,
                candidates: [
                  {
                    first: 'Donald',
                    last: 'Trump',
                    party: 'Rep',
                    incumbent: true,
                    candidateID: '51896',
                    polID: '0',
                    ballotOrder: 1,
                    polNum: '49353',
                    voteCount: 10000,
                    winner: 'X',
                  },
                  {
                    first: 'Joe',
                    last: 'Biden',
                    party: 'Dem',
                    candidateID: '52107',
                    polID: '0',
                    ballotOrder: 2,
                    polNum: '49500',
                    voteCount: 8000,
                  },
                ],
              },
            ],
          },
          {
            test: false,
            resultsType: 'live',
            raceID: '0',
            raceType: 'General',
            raceTypeID: 'G',
            officeID: 'P',
            officeName: 'President',
            reportingUnits: [
              {
                statePostal: 'US',
                stateName: 'United States',
                level: 'national',
                lastUpdated: '2021-06-09T20:35:40.840Z',
                precinctsReporting: 2584,
                precinctsTotal: 2584,
                precinctsReportingPct: 100,
                candidates: [
                  {
                    first: 'Donald',
                    last: 'Trump',
                    party: 'Rep',
                    incumbent: true,
                    candidateID: '51896',
                    polID: '0',
                    ballotOrder: 1,
                    polNum: '49353',
                    voteCount: 280076,
                  },
                  {
                    first: 'Joe',
                    last: 'Biden',
                    party: 'Dem',
                    candidateID: '52107',
                    polID: '0',
                    ballotOrder: 2,
                    polNum: '49500',
                    voteCount: 271187,
                    winner: 'X',
                  },
                ],
              },
              {
                statePostal: 'VA',
                stateName: 'Virginia',
                level: 'state',
                lastUpdated: '2021-06-09T20:35:40.840Z',
                precinctsReporting: 2584,
                precinctsTotal: 2584,
                precinctsReportingPct: 100,
                candidates: [
                  {
                    first: 'Donald',
                    last: 'Trump',
                    party: 'Rep',
                    incumbent: true,
                    candidateID: '51896',
                    polID: '0',
                    ballotOrder: 1,
                    polNum: '49353',
                    voteCount: 10000,
                    winner: 'X',
                  },
                  {
                    first: 'Joe',
                    last: 'Biden',
                    party: 'Dem',
                    candidateID: '52107',
                    polID: '0',
                    ballotOrder: 2,
                    polNum: '49500',
                    voteCount: 8000,
                  },
                ],
              },
            ],
          },
        ],
        nextrequest:
          'https://api.ap.org/v2/elections/2021-06-08?format=json&level=state&officeid=A&racetypeid=D&resultstype=l&statepostal=VA&winner=X&minDateTime=2021-06-09T20%3a35%3a40.840Z',
      },
      [
        'Content-Type',
        'application/json',
        'Content-Length',
        '929',
        'Connection',
        'close',
        'Date',
        'Tue, 12 Oct 2021 15:41:05 GMT',
        'x-amzn-RequestId',
        'd38f92b4-b1eb-4941-8522-dd732217f233',
        'Last-Modified',
        'Wed, 09 Jun 2021 20:35:40 GMT',
        'x-electionsapi-Q-minute-secondsLeft',
        '56',
        'x-electionsapi-Q-minute-used',
        '1',
        'x-electionsapi-Q-minute-allowed',
        '10',
        'x-electionsapi-Q-minute-available',
        '9',
        'x-amzn-Remapped-Connection',
        'keep-alive',
        'x-electionsapi-Q-minute-name',
        'elections',
        'x-amz-apigw-id',
        'HGfmvHv-IAMFdfw=',
        'Cache-Control',
        'private',
        'ETag',
        '"c361e0ea77eceb267b3c2233c0a376e0-20210609203540840-JSON"',
        'x-nancygzip',
        'noreq',
        'x-electionsapi-sid',
        'd38f92b4-b1eb-4941-8522-dd732217f233',
        'X-Amzn-Trace-Id',
        'Root=1-6165ac91-4b23e59d2657db775f2627a8',
        'x-amzn-Remapped-date',
        'Tue, 12 Oct 2021 15:41:04 GMT',
        'X-Cache',
        'Miss from cloudfront',
        'Via',
        '1.1 4f87745990545c1ac0195c157e1668f8.cloudfront.net (CloudFront)',
        'X-Amz-Cf-Pop',
        'HIO50-C1',
        'X-Amz-Cf-Id',
        'zkTR6tAkwmYZBYZXIx9Ix4dMC36_CikTNkqLYuSBn-sJW7mDAgnVuw==',
      ],
    )
}

export const mockResponseWithNationalAndState = (apikey) => {
  nock('https://api.ap.org/v2', { encodedQueryParams: true })
    .get('/elections/2020-11-08')
    .query({
      statePostal: 'US',
      officeID: 'P',
      level: 'state',
      raceTypeID: 'G',
      format: 'json',
      winner: 'X',
      resultsType: 'l',
      apikey,
    })
    .reply(
      200,
      {
        electionDate: '2021-06-08',
        timestamp: '2021-10-12T15:41:05.383Z',
        races: [
          {
            test: false,
            resultsType: 'live',
            raceID: '0',
            raceType: 'General',
            raceTypeID: 'G',
            officeID: 'P',
            officeName: 'President',
            reportingUnits: [
              {
                statePostal: 'US',
                stateName: 'United States',
                level: 'national',
                lastUpdated: '2021-06-09T20:35:40.840Z',
                precinctsReporting: 2584,
                precinctsTotal: 2584,
                precinctsReportingPct: 100,
                candidates: [
                  {
                    first: 'Donald',
                    last: 'Trump',
                    party: 'Rep',
                    incumbent: true,
                    candidateID: '51896',
                    polID: '0',
                    ballotOrder: 1,
                    polNum: '49353',
                    voteCount: 280076,
                  },
                  {
                    first: 'Joe',
                    last: 'Biden',
                    party: 'Dem',
                    candidateID: '52107',
                    polID: '0',
                    ballotOrder: 2,
                    polNum: '49500',
                    voteCount: 271187,
                    winner: 'X',
                  },
                ],
              },
              {
                statePostal: 'VA',
                stateName: 'Virginia',
                level: 'state',
                lastUpdated: '2021-06-09T20:35:40.840Z',
                precinctsReporting: 2584,
                precinctsTotal: 2584,
                precinctsReportingPct: 100,
                candidates: [
                  {
                    first: 'Donald',
                    last: 'Trump',
                    party: 'Rep',
                    incumbent: true,
                    candidateID: '51896',
                    polID: '0',
                    ballotOrder: 1,
                    polNum: '49353',
                    voteCount: 10000,
                    winner: 'X',
                  },
                  {
                    first: 'Joe',
                    last: 'Biden',
                    party: 'Dem',
                    candidateID: '52107',
                    polID: '0',
                    ballotOrder: 2,
                    polNum: '49500',
                    voteCount: 8000,
                  },
                ],
              },
            ],
          },
        ],
        nextrequest:
          'https://api.ap.org/v2/elections/2021-06-08?format=json&level=state&officeid=A&racetypeid=D&resultstype=l&statepostal=VA&winner=X&minDateTime=2021-06-09T20%3a35%3a40.840Z',
      },
      [
        'Content-Type',
        'application/json',
        'Content-Length',
        '929',
        'Connection',
        'close',
        'Date',
        'Tue, 12 Oct 2021 15:41:05 GMT',
        'x-amzn-RequestId',
        'd38f92b4-b1eb-4941-8522-dd732217f233',
        'Last-Modified',
        'Wed, 09 Jun 2021 20:35:40 GMT',
        'x-electionsapi-Q-minute-secondsLeft',
        '56',
        'x-electionsapi-Q-minute-used',
        '1',
        'x-electionsapi-Q-minute-allowed',
        '10',
        'x-electionsapi-Q-minute-available',
        '9',
        'x-amzn-Remapped-Connection',
        'keep-alive',
        'x-electionsapi-Q-minute-name',
        'elections',
        'x-amz-apigw-id',
        'HGfmvHv-IAMFdfw=',
        'Cache-Control',
        'private',
        'ETag',
        '"c361e0ea77eceb267b3c2233c0a376e0-20210609203540840-JSON"',
        'x-nancygzip',
        'noreq',
        'x-electionsapi-sid',
        'd38f92b4-b1eb-4941-8522-dd732217f233',
        'X-Amzn-Trace-Id',
        'Root=1-6165ac91-4b23e59d2657db775f2627a8',
        'x-amzn-Remapped-date',
        'Tue, 12 Oct 2021 15:41:04 GMT',
        'X-Cache',
        'Miss from cloudfront',
        'Via',
        '1.1 4f87745990545c1ac0195c157e1668f8.cloudfront.net (CloudFront)',
        'X-Amz-Cf-Pop',
        'HIO50-C1',
        'X-Amz-Cf-Id',
        'zkTR6tAkwmYZBYZXIx9Ix4dMC36_CikTNkqLYuSBn-sJW7mDAgnVuw==',
      ],
    )
}

export const mockStatusLevelResponse = (apikey) => {
  nock('https://api.ap.org/v2', { encodedQueryParams: true })
    .get('/elections/2021-06-08')
    .query({
      statePostal: 'CA',
      officeID: 'A',
      level: 'state',
      raceTypeID: 'D',
      format: 'json',
      winner: 'X',
      resultsType: 'l',
      apikey,
    })
    .reply(
      200,
      {
        electionDate: '2021-06-08',
        timestamp: '2021-10-12T15:41:05.383Z',
        races: [
          {
            test: false,
            resultsType: 'live',
            raceID: '47227',
            raceType: 'Primary',
            raceTypeID: 'D',
            officeID: 'A',
            officeName: 'Attorney General',
            party: 'Dem',
            reportingUnits: [
              {
                statePostal: 'VA',
                stateName: 'Virginia',
                level: 'state',
                lastUpdated: '2021-06-09T20:35:40.840Z',
                precinctsReporting: 2584,
                precinctsTotal: 2584,
                precinctsReportingPct: 100,
                candidates: [
                  {
                    first: 'Mark',
                    last: 'Herring',
                    party: 'Dem',
                    incumbent: true,
                    candidateID: '51896',
                    polID: '0',
                    ballotOrder: 1,
                    polNum: '49353',
                    voteCount: 271187,
                    winner: 'X',
                  },
                  {
                    first: 'Jerrauld',
                    last: 'Jones',
                    party: 'Dem',
                    candidateID: '52107',
                    polID: '0',
                    ballotOrder: 2,
                    polNum: '49500',
                    voteCount: 207792,
                  },
                ],
              },
            ],
          },
        ],
        nextrequest:
          'https://api.ap.org/v2/elections/2021-06-08?format=json&level=state&officeid=A&racetypeid=D&resultstype=l&statepostal=VA&winner=X&minDateTime=2021-06-09T20%3a35%3a40.840Z',
      },
      [
        'Content-Type',
        'application/json',
        'Content-Length',
        '929',
        'Connection',
        'close',
        'Date',
        'Tue, 12 Oct 2021 15:41:05 GMT',
        'x-amzn-RequestId',
        'd38f92b4-b1eb-4941-8522-dd732217f233',
        'Last-Modified',
        'Wed, 09 Jun 2021 20:35:40 GMT',
        'x-electionsapi-Q-minute-secondsLeft',
        '56',
        'x-electionsapi-Q-minute-used',
        '1',
        'x-electionsapi-Q-minute-allowed',
        '10',
        'x-electionsapi-Q-minute-available',
        '9',
        'x-amzn-Remapped-Connection',
        'keep-alive',
        'x-electionsapi-Q-minute-name',
        'elections',
        'x-amz-apigw-id',
        'HGfmvHv-IAMFdfw=',
        'Cache-Control',
        'private',
        'ETag',
        '"c361e0ea77eceb267b3c2233c0a376e0-20210609203540840-JSON"',
        'x-nancygzip',
        'noreq',
        'x-electionsapi-sid',
        'd38f92b4-b1eb-4941-8522-dd732217f233',
        'X-Amzn-Trace-Id',
        'Root=1-6165ac91-4b23e59d2657db775f2627a8',
        'x-amzn-Remapped-date',
        'Tue, 12 Oct 2021 15:41:04 GMT',
        'X-Cache',
        'Miss from cloudfront',
        'Via',
        '1.1 4f87745990545c1ac0195c157e1668f8.cloudfront.net (CloudFront)',
        'X-Amz-Cf-Pop',
        'HIO50-C1',
        'X-Amz-Cf-Id',
        'zkTR6tAkwmYZBYZXIx9Ix4dMC36_CikTNkqLYuSBn-sJW7mDAgnVuw==',
      ],
    )
}
