#!/bin/bash

# Required environment variable examples
# IMAGE_NAME=public.ecr.aws/chainlink/adapters/example-source-adapter:1.0.0
# ADAPTER_NAME=example-source-adapter
# AWS_ECR_PRIAVTE=true
# AWS_REGION=us-west-2

# Extract the image tag out of the generated image name, since the tag comes immediately after a ":"
echo "Extracting image tag from image name ${IMAGE_NAME}..."
image_tag=$(echo "$IMAGE_NAME" | awk -F: '{print $2}')
echo "Extracted $image_tag from $IMAGE_NAME"

# For either ECR public or private, see if an image exists by fetching its metadata
if [ "$AWS_ECR_PRIVATE" == "true" ]; then
  aws_cmd="ecr"
else
  aws_cmd="ecr-public"
fi

aws "$aws_cmd" describe-images \
  --repository-name "adapters/$ADAPTER_NAME" \
  --image-ids "imageTag=$image_tag"

RC=$?
if [ $RC -eq "0" ]; then
  echo "Found existing image"
  echo "::set-output name=image-exists::true"
else
  echo "Did not find existing image"
  echo "::set-output name=image-exists::false"
fi
