import * as shell from 'shelljs'

describe('readme generation script', () => {
  const doReadmeTest = (pathToAdapter) => {
    const generatedReadmePath = pathToAdapter + 'README.md'

    // Delete the README and make sure it's gone to be sure what we compare
    // is actually generated by the script.
    shell.rm(generatedReadmePath)
    expect(shell.test('-f', generatedReadmePath)).toBe(false)

    shell.exec(`yarn generate:readme -t ${pathToAdapter}`)

    let readmeString = shell.cat(generatedReadmePath).toString()

    // Replace version # to prevent test from failing on every upgrade
    const semverRegex = new RegExp(/\[[0-9]+(\.[0-9]+)*\]/)
    readmeString = readmeString.replace(semverRegex, '[X.X.X]')

    expect(readmeString).toMatchSnapshot()
  }

  describe('when generating readme for readme-test-adapter', () => {
    it('should successfully generate readme', async () => {
      const pathToAdapter =
        'packages/scripts/src/generate-readme/test/integration/readme-test-adapter/'
      doReadmeTest(pathToAdapter)
    })
  })

  describe('when generating readme for readme-test-v3-adapter', () => {
    it('should successfully generate readme', async () => {
      const pathToAdapter =
        'packages/scripts/src/generate-readme/test/integration/readme-test-v3-adapter/'
      // V3 adapters have their README generated based on the built code, so we
      // need to build before generating the README.
      shell.exec(`yarn --cwd ${pathToAdapter} build`)
      doReadmeTest(pathToAdapter)
    })
  })
})
