apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 1
  replicas: {{ .Values.replicas }}
  template:
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Values.name }}
          image: {{ print .Values.image.repository (hasPrefix "sha256:" .Values.image.tag | ternary "@" ":") .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: qa-github-token
                  key: GITHUB_TOKEN
