import nock from 'nock'

export const config = {
  ACCESS_KEY: 'fake-access-key',
  PASSPHRASE: 'fake-passphrase',
  SIGNING_KEY: 'fake-signing-key',
  PORTFOLIO_ID: 'fake-portfolio',
}
export const mockResponseSuccess = (): nock.Scope =>
  nock('https://api.prime.coinbase.com/v1', {
    encodedQueryParams: true,
    // reqheaders: {
    //   'X-Api-Key': 'fake-api-key',
    // },
  })
    .get(`/portfolios/${config.PORTFOLIO_ID}/balances?balance_type=TRADING_BALANCES`)
    // .query({ apikey: 'fake-api-key', amount: 1, precision: 6 })
    .reply(
      200,
      () => ({
        balances: [
          {
            symbol: 'aave',
            amount: '41.03',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '41.03',
          },
          {
            symbol: 'eos',
            amount: '3128.2',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '3128.2',
          },
          {
            symbol: 'near',
            amount: '2535.958',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '2535.958',
          },
          {
            symbol: 'usdc',
            amount: '0.558334',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '0.558334',
          },
          {
            symbol: 'xtz',
            amount: '0.41',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '0.41',
          },
          {
            symbol: 'fil',
            amount: '1069.358',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '1069.358',
          },
          {
            symbol: 'doge',
            amount: '345906',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '345906',
          },
          {
            symbol: 'etc',
            amount: '398.88',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '398.88',
          },
          {
            symbol: 'btc',
            amount: '4.680791',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '4.680791',
          },
          {
            symbol: 'dot',
            amount: '3323.806',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '3323.806',
          },
          {
            symbol: 'xlm',
            amount: '75378',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '75378',
          },
          {
            symbol: 'bch',
            amount: '54.254',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '54.254',
          },
          {
            symbol: 'matic',
            amount: '23892.3',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '23892.3',
          },
          {
            symbol: 'ape',
            amount: '1043.79',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '1043.79',
          },
          {
            symbol: 'shib',
            amount: '1546636747',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '1546636747',
          },
          {
            symbol: 'sol',
            amount: '1064.831',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '1064.831',
          },
          {
            symbol: 'mana',
            amount: '2.6',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '2.6',
          },
          {
            symbol: 'qnt',
            amount: '35.442',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '35.442',
          },
          {
            symbol: 'chz',
            amount: '13',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '13',
          },
          {
            symbol: 'cro',
            amount: '72410',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '72410',
          },
          {
            symbol: 'atom',
            amount: '804.5',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '804.5',
          },
          {
            symbol: 'icp',
            amount: '802.8',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '802.8',
          },
          {
            symbol: 'eth',
            amount: '40.438',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '40.438',
          },
          {
            symbol: 'uni',
            amount: '2193.1',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '2193.1',
          },
          {
            symbol: 'stx',
            amount: '0',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '0',
          },
          {
            symbol: 'ltc',
            amount: '195.48',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '195.48',
          },
          {
            symbol: 'ada',
            amount: '95078.9',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '95078.9',
          },
          {
            symbol: 'avax',
            amount: '856.607',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '856.607',
          },
          {
            symbol: 'link',
            amount: '1459.04',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '1459.04',
          },
          {
            symbol: 'algo',
            amount: '20849',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '20849',
          },
          {
            symbol: 'nu',
            amount: '0',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '0',
          },
          {
            symbol: 'usd',
            amount: '58430.19604095414522',
            holds: '0',
            bonded_amount: '',
            reserved_amount: '',
            unbonding_amount: '',
            unvested_amount: '',
            pending_rewards_amount: '',
            past_rewards_amount: '',
            bondable_amount: '',
            withdrawable_amount: '58430.19604095414522',
          },
        ],
        type: 'TRADING_BALANCES',
        trading_balances: { total: '548110.72', holds: '0' },
        vault_balances: { total: '1704768.10', holds: '1.18' },
      }),
      [
        'Content-Type',
        'application/json',
        'Connection',
        'close',
        'Vary',
        'Accept-Encoding',
        'Vary',
        'Origin',
      ],
    )
