name: Matrix Adapters

description: Read build strategy matrix of adapters, from a json file

inputs:
  BUILD_ALL:
    description: 'If true, build all adapters'
    required: false
    default: 'false'
outputs:
  result:
    value: ${{ steps.create-matrix.outputs.result }}
    description: 'An object containing the matrix of adapters to build'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/setup
    - name: Generate job matrix
      id: create-matrix
      shell: bash
      run: yarn generate:gha:matrix
      env:
        BUILD_ALL: ${{ github.event.inputs.BUILD_ALL }}
