name: Matrix Adapters

description: Read build strategy matrix of adapters, from a json file

inputs:
  branch:
    description: The current branch this workflow is running from, to include in an image tag, omit if you do not want to have the branch included in the image tag.
    required: false
  latest:
    description: Set to "true" to create an image tag with the "latest" tag, "false" to use the external adapter's package.json version instead.
    required: false

outputs:
  result:
    value: ${{ steps.create-matrix.outputs.result }}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Generate job matrix
      id: create-matrix
      shell: bash
      run: yarn generate:gha:matrix
      env:
        BRANCH: ${{ inputs.branch }}
        LATEST: ${{ inputs.latest }}
