export const AdapterStubs: Record<string, any> = {
  TOKEN_ALLOCATION: {
    jobRunID: '1',
    data: {
      COMP: {
        quote: {
          USD: {
            price: '192.23560377',
          },
        },
      },
      MKR: {
        quote: {
          USD: {
            price: '1285.07135635',
          },
        },
      },
      AAVE: {
        quote: {
          USD: {
            price: '173.18073267',
          },
        },
      },
      UMA: {
        quote: {
          USD: {
            price: '10.20122460',
          },
        },
      },
      SNX: {
        quote: {
          USD: {
            price: '13.62490473',
          },
        },
      },
      REN: {
        quote: {
          USD: {
            price: '0.68786796',
          },
        },
      },
      UNI: {
        quote: {
          USD: {
            price: '8.23570852',
          },
        },
      },
      KNC: {
        quote: {
          USD: {
            price: '1.26141751',
          },
        },
      },
      CRV: {
        quote: {
          USD: {
            price: '1.75094267',
          },
        },
      },
      WNXM: {
        quote: {
          USD: {
            price: '39.17240510',
          },
        },
      },
      YFI: {
        quote: {
          USD: {
            price: '30967.53680584',
          },
        },
      },
      BAL: {
        quote: {
          USD: {
            price: '20.15973056',
          },
        },
      },
      result: 40.12795,
    },
    result: 40.12795,
    statusCode: 200,
  },
  SYNTHETIX: [
    {
      asset: 'USD',
      category: 'forex',
      sign: '$',
      description: 'US Dollars',
      name: 'sUSD',
      subclass: 'MultiCollateralSynth',
    },
    {
      feed: '0xb49f677943BC038e9857d61E7d053CaA2C1734C1',
      asset: 'EUR',
      category: 'forex',
      sign: '€',
      description: 'Euros',
      name: 'sEUR',
    },
    {
      feed: '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3',
      asset: 'JPY',
      category: 'forex',
      sign: '¥',
      description: 'Japanese Yen',
      name: 'sJPY',
    },
    {
      feed: '0x77F9710E7d0A19669A13c055F62cd80d313dF022',
      asset: 'AUD',
      category: 'forex',
      sign: '$',
      description: 'Australian Dollars',
      name: 'sAUD',
    },
    {
      feed: '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5',
      asset: 'GBP',
      category: 'forex',
      sign: '£',
      description: 'Pound Sterling',
      name: 'sGBP',
    },
    {
      feed: '0x449d117117838fFA61263B61dA6301AA2a88B13A',
      asset: 'CHF',
      category: 'forex',
      sign: 'Fr',
      description: 'Swiss Franc',
      name: 'sCHF',
    },
    {
      feed: '0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6',
      asset: 'XAU',
      category: 'commodity',
      sign: 'oz',
      description: 'Gold Ounce',
      name: 'sXAU',
    },
    {
      feed: '0x379589227b15F1a12195D3f2d90bBc9F31f95235',
      asset: 'XAG',
      category: 'commodity',
      sign: 'oz',
      description: 'Silver Ounce',
      name: 'sXAG',
    },
    {
      feed: '0xf3584F4dd3b467e73C2339EfD008665a70A4185c',
      asset: 'OIL',
      category: 'commodity',
      sign: '$',
      description: 'Perpetual Oil Futures',
      name: 'sOIL',
    },
    {
      feed: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c',
      asset: 'BTC',
      category: 'crypto',
      sign: '₿',
      description: 'Bitcoin',
      name: 'sBTC',
      subclass: 'MultiCollateralSynth',
    },
    {
      feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
      asset: 'ETH',
      category: 'crypto',
      sign: 'Ξ',
      description: 'Ether',
      name: 'sETH',
      subclass: 'MultiCollateralSynth',
    },
    {
      feed: '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A',
      asset: 'BNB',
      category: 'crypto',
      sign: '',
      description: 'Binance Coin',
      name: 'sBNB',
      subclass: 'PurgeableSynth',
    },
    {
      feed: '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25',
      asset: 'TRX',
      category: 'crypto',
      sign: '',
      description: 'TRON',
      name: 'sTRX',
    },
    {
      feed: '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F',
      asset: 'XTZ',
      category: 'crypto',
      sign: '',
      description: 'Tezos',
      name: 'sXTZ',
      subclass: 'PurgeableSynth',
    },
    {
      feed: '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12',
      asset: 'XRP',
      category: 'crypto',
      sign: '',
      description: 'Ripple',
      name: 'sXRP',
    },
    {
      feed: '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B',
      asset: 'LTC',
      category: 'crypto',
      sign: '',
      description: 'Litecoin',
      name: 'sLTC',
      subclass: 'PurgeableSynth',
    },
    {
      feed: '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c',
      asset: 'LINK',
      category: 'crypto',
      sign: '',
      description: 'Chainlink',
      name: 'sLINK',
    },
    {
      feed: '0x10a43289895eAff840E8d45995BBa89f9115ECEe',
      asset: 'EOS',
      category: 'crypto',
      sign: '',
      description: 'EOS',
      name: 'sEOS',
    },
    {
      feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2',
      asset: 'ETC',
      category: 'crypto',
      sign: '',
      description: 'Ethereum Classic',
      name: 'sETC',
    },
    {
      feed: '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912',
      asset: 'DASH',
      category: 'crypto',
      sign: '',
      description: 'Dash',
      name: 'sDASH',
    },
    {
      feed: '0xFA66458Cce7Dd15D8650015c4fce4D278271618F',
      asset: 'XMR',
      category: 'crypto',
      sign: '',
      description: 'Monero',
      name: 'sXMR',
    },
    {
      feed: '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55',
      asset: 'ADA',
      category: 'crypto',
      sign: '',
      description: 'Cardano',
      name: 'sADA',
    },
    {
      feed: '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9',
      asset: 'AAVE',
      category: 'crypto',
      sign: '',
      description: 'Aave',
      name: 'sAAVE',
    },
    {
      feed: '0x553303d460EE0afB37EdFf9bE42922D8FF63220e',
      asset: 'UNI',
      category: 'crypto',
      sign: '',
      description: 'Uniswap',
      name: 'sUNI',
    },
    {
      feed: '0xA027702dbb89fbd58938e4324ac03B58d812b0E1',
      asset: 'YFI',
      category: 'crypto',
      sign: '',
      description: 'yearn.finance',
      name: 'sYFI',
    },
    {
      feed: '0x1C07AFb8E2B827c5A4739C6d59Ae3A5035f28734',
      asset: 'DOT',
      category: 'crypto',
      sign: '',
      description: 'Polkadot',
      name: 'sDOT',
    },
    {
      feed: '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01',
      asset: 'REN',
      category: 'crypto',
      sign: '',
      description: 'Ren',
      name: 'sREN',
    },
    {
      feed: '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5',
      asset: 'COMP',
      category: 'crypto',
      sign: '',
      description: 'Compound',
      name: 'sCOMP',
    },
    {
      feed: '0xE23FA0e8dd05D6f66a6e8c98cab2d9AE82A7550c',
      asset: 'FTSE100',
      category: 'equities',
      sign: '',
      exchange: 'LSE',
      description: 'FTSE 100 Index',
      name: 'sFTSE',
    },
    {
      feed: '0x5c4939a2ab3A2a9f93A518d81d4f8D0Bc6a68980',
      asset: 'NIKKEI225',
      category: 'equities',
      sign: '',
      exchange: 'TSE',
      description: 'Nikkei 225 Index',
      name: 'sNIKKEI',
    },
    {
      feed: '0x1ceDaaB50936881B3e449e47e40A2cDAF5576A4a',
      asset: 'TSLA',
      category: 'equities',
      sign: '',
      exchange: 'NASDAQ',
      description: 'Tesla',
      name: 'sTSLA',
    },
    {
      feed: '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2',
      asset: 'CEX',
      category: 'index',
      sign: '',
      description: 'Centralised Exchange Index',
      name: 'sCEX',
      index: [
        {
          asset: 'BNB',
          category: 'crypto',
          sign: '',
          description: 'Binance Coin',
          units: 12.88,
          weight: 29.15,
        },
        {
          asset: 'CRO',
          category: 'crypto',
          sign: '',
          description: 'Crypto com',
          units: 1303.31,
          weight: 24.3,
        },
        {
          asset: 'LEO',
          category: 'crypto',
          sign: '',
          description: 'UNUS SED LEO',
          units: 94.54,
          weight: 13.42,
        },
        {
          asset: 'HT',
          category: 'crypto',
          sign: '',
          description: 'Huobi Token',
          units: 23.06,
          weight: 11.73,
        },
        {
          asset: 'FTT',
          category: 'crypto',
          sign: '',
          description: 'FTX',
          units: 9.36,
          weight: 3.56,
        },
        {
          asset: 'OKB',
          category: 'crypto',
          sign: '',
          description: 'OKB',
          units: 25.72,
          weight: 16.97,
        },
        {
          asset: 'KCS',
          category: 'crypto',
          sign: '',
          description: 'KuCoin Shares',
          units: 9.18,
          weight: 0.87,
        },
      ],
      subclass: 'PurgeableSynth',
    },
    {
      feed: '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87',
      asset: 'DEFI',
      category: 'index',
      sign: '',
      description: 'DeFi Index',
      name: 'sDEFI',
      index: [
        {
          asset: 'COMP',
          category: 'crypto',
          sign: '',
          description: 'Compound',
          units: 1.55,
          weight: 5,
        },
        {
          asset: 'MKR',
          category: 'crypto',
          sign: '',
          description: 'Maker',
          units: 0.54,
          weight: 10,
        },
        {
          asset: 'AAVE',
          category: 'crypto',
          sign: '',
          description: 'Aave',
          units: 4.72,
          weight: 15,
        },
        { asset: 'UMA', category: 'crypto', sign: '', description: 'UMA', units: 26.06, weight: 5 },
        {
          asset: 'SNX',
          category: 'crypto',
          sign: '',
          description: 'Synthetix Network Token',
          units: 87.2,
          weight: 15,
        },
        {
          asset: 'REN',
          category: 'crypto',
          sign: '',
          description: 'Ren',
          units: 680.59,
          weight: 5,
        },
        {
          asset: 'UNI',
          category: 'crypto',
          sign: '',
          description: 'Uniswap',
          units: 100.71,
          weight: 15,
        },
        {
          asset: 'KNC',
          category: 'crypto',
          sign: '',
          description: 'Kyber Network',
          units: 334.06,
          weight: 5,
        },
        {
          asset: 'CRV',
          category: 'crypto',
          sign: '',
          description: 'Curve DAO Token',
          units: 254.94,
          weight: 5,
        },
        { asset: 'SUSHI', units: 43.111, weight: 5 },
        {
          asset: 'YFI',
          category: 'crypto',
          sign: '',
          description: 'yearn.finance',
          units: 0.01604,
          weight: 5,
        },
        {
          asset: 'BAL',
          category: 'crypto',
          sign: '',
          description: 'Balancer',
          units: 14.84,
          weight: 5,
        },
        {
          asset: 'BNT',
          category: 'crypto',
          sign: '',
          description: 'Bancor',
          units: 90.661,
          weight: 2.5,
        },
        { asset: '1INCH', units: 71.837, weight: 2.5 },
      ],
      subclass: 'PurgeableSynth',
    },
    {
      feed: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c',
      asset: 'BTC',
      category: 'crypto',
      sign: '₿',
      description: 'Inverse Bitcoin',
      name: 'iBTC',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 40378, upperLimit: 60567, lowerLimit: 20189 },
    },
    {
      feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
      asset: 'ETH',
      category: 'crypto',
      sign: 'Ξ',
      description: 'Inverse Ether',
      name: 'iETH',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 1548, upperLimit: 2322, lowerLimit: 774 },
    },
    {
      feed: '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A',
      asset: 'BNB',
      category: 'crypto',
      sign: '',
      description: 'Inverse Binance Coin',
      name: 'iBNB',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 50.958, upperLimit: 76.437, lowerLimit: 25.479 },
    },
    {
      feed: '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25',
      asset: 'TRX',
      category: 'crypto',
      sign: '',
      description: 'Inverse TRON',
      name: 'iTRX',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 0.0331, upperLimit: 0.0497, lowerLimit: 0.0166 },
    },
    {
      feed: '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F',
      asset: 'XTZ',
      category: 'crypto',
      sign: '',
      description: 'Inverse Tezos',
      name: 'iXTZ',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 2.542, upperLimit: 3.813, lowerLimit: 1.271 },
    },
    {
      feed: '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12',
      asset: 'XRP',
      category: 'crypto',
      sign: '',
      description: 'Inverse Ripple',
      name: 'iXRP',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 0.3757, upperLimit: 0.5636, lowerLimit: 0.1879 },
    },
    {
      feed: '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c',
      asset: 'LINK',
      category: 'crypto',
      sign: '',
      description: 'Inverse Chainlink',
      name: 'iLINK',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 22.6, upperLimit: 33.9, lowerLimit: 11.3 },
    },
    {
      feed: '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B',
      asset: 'LTC',
      category: 'crypto',
      sign: '',
      description: 'Inverse Litecoin',
      name: 'iLTC',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 131.812, upperLimit: 197.718, lowerLimit: 65.906 },
    },
    {
      feed: '0x10a43289895eAff840E8d45995BBa89f9115ECEe',
      asset: 'EOS',
      category: 'crypto',
      sign: '',
      description: 'Inverse EOS',
      name: 'iEOS',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 3.0431, upperLimit: 4.5647, lowerLimit: 1.5216 },
    },
    {
      feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2',
      asset: 'ETC',
      category: 'crypto',
      sign: '',
      description: 'Inverse Ethereum Classic',
      name: 'iETC',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 7.46, upperLimit: 11.19, lowerLimit: 3.73 },
    },
    {
      feed: '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912',
      asset: 'DASH',
      category: 'crypto',
      sign: '',
      description: 'Inverse Dash',
      name: 'iDASH',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 105.58, upperLimit: 158.37, lowerLimit: 52.79 },
    },
    {
      feed: '0xFA66458Cce7Dd15D8650015c4fce4D278271618F',
      asset: 'XMR',
      category: 'crypto',
      sign: '',
      description: 'Inverse Monero',
      name: 'iXMR',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 132.26, upperLimit: 198.4, lowerLimit: 66.13 },
    },
    {
      feed: '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55',
      asset: 'ADA',
      category: 'crypto',
      sign: '',
      description: 'Inverse Cardano',
      name: 'iADA',
      subclass: 'PurgeableSynth',
      inverted: {
        entryPoint: 0.388,
        upperLimit: 0.582,
        lowerLimit: 0.194,
      },
    },
    {
      feed: '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2',
      asset: 'CEX',
      category: 'index',
      sign: '',
      description: 'Inverse Centralised Exchange Index',
      name: 'iCEX',
      index: [
        {
          asset: 'BNB',
          category: 'crypto',
          sign: '',
          description: 'Binance Coin',
          units: 12.88,
          weight: 29.15,
        },
        {
          asset: 'CRO',
          category: 'crypto',
          sign: '',
          description: 'Crypto com',
          units: 1303.31,
          weight: 24.3,
        },
        {
          asset: 'LEO',
          category: 'crypto',
          sign: '',
          description: 'UNUS SED LEO',
          units: 94.54,
          weight: 13.42,
        },
        {
          asset: 'HT',
          category: 'crypto',
          sign: '',
          description: 'Huobi Token',
          units: 23.06,
          weight: 11.73,
        },
        {
          asset: 'FTT',
          category: 'crypto',
          sign: '',
          description: 'FTX',
          units: 9.36,
          weight: 3.56,
        },
        {
          asset: 'OKB',
          category: 'crypto',
          sign: '',
          description: 'OKB',
          units: 25.72,
          weight: 16.97,
        },
        {
          asset: 'KCS',
          category: 'crypto',
          sign: '',
          description: 'KuCoin Shares',
          units: 9.18,
          weight: 0.87,
        },
      ],
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 988.56, upperLimit: 1482.84, lowerLimit: 494.28 },
    },
    {
      feed: '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87',
      asset: 'DEFI',
      category: 'index',
      sign: '',
      description: 'Inverse DeFi Index',
      name: 'iDEFI',
      index: [
        {
          asset: 'COMP',
          category: 'crypto',
          sign: '',
          description: 'Compound',
          units: 1.55,
          weight: 5,
        },
        {
          asset: 'MKR',
          category: 'crypto',
          sign: '',
          description: 'Maker',
          units: 0.54,
          weight: 10,
        },
        {
          asset: 'AAVE',
          category: 'crypto',
          sign: '',
          description: 'Aave',
          units: 4.72,
          weight: 15,
        },
        { asset: 'UMA', category: 'crypto', sign: '', description: 'UMA', units: 26.06, weight: 5 },
        {
          asset: 'SNX',
          category: 'crypto',
          sign: '',
          description: 'Synthetix Network Token',
          units: 87.2,
          weight: 15,
        },
        {
          asset: 'REN',
          category: 'crypto',
          sign: '',
          description: 'Ren',
          units: 680.59,
          weight: 5,
        },
        {
          asset: 'UNI',
          category: 'crypto',
          sign: '',
          description: 'Uniswap',
          units: 100.71,
          weight: 15,
        },
        {
          asset: 'KNC',
          category: 'crypto',
          sign: '',
          description: 'Kyber Network',
          units: 334.06,
          weight: 5,
        },
        {
          asset: 'CRV',
          category: 'crypto',
          sign: '',
          description: 'Curve DAO Token',
          units: 254.94,
          weight: 5,
        },
        { asset: 'SUSHI', units: 43.111, weight: 5 },
        {
          asset: 'YFI',
          category: 'crypto',
          sign: '',
          description: 'yearn.finance',
          units: 0.01604,
          weight: 5,
        },
        {
          asset: 'BAL',
          category: 'crypto',
          sign: '',
          description: 'Balancer',
          units: 14.84,
          weight: 5,
        },
        {
          asset: 'BNT',
          category: 'crypto',
          sign: '',
          description: 'Bancor',
          units: 90.661,
          weight: 2.5,
        },
        { asset: '1INCH', units: 71.837, weight: 2.5 },
      ],
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 10048.068, upperLimit: 15072.102, lowerLimit: 5024.034 },
    },
    {
      feed: '0xf3584F4dd3b467e73C2339EfD008665a70A4185c',
      asset: 'OIL',
      category: 'commodity',
      sign: '$',
      description: 'Inverse Perpetual Oil Futures',
      name: 'iOIL',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 45.087, upperLimit: 67.63, lowerLimit: 22.543 },
    },
    {
      feed: '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9',
      asset: 'AAVE',
      category: 'crypto',
      sign: '',
      description: 'Inverse Aave',
      name: 'iAAVE',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 406, upperLimit: 609, lowerLimit: 203 },
    },
    {
      feed: '0x553303d460EE0afB37EdFf9bE42922D8FF63220e',
      asset: 'UNI',
      category: 'crypto',
      sign: '',
      description: 'Inverse Uniswap',
      name: 'iUNI',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 21, upperLimit: 31.5, lowerLimit: 10.5 },
    },
    {
      feed: '0xA027702dbb89fbd58938e4324ac03B58d812b0E1',
      asset: 'YFI',
      category: 'crypto',
      sign: '',
      description: 'Inverse yearn.finance',
      name: 'iYFI',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 33300, upperLimit: 49950, lowerLimit: 16650 },
    },
    {
      feed: '0x1C07AFb8E2B827c5A4739C6d59Ae3A5035f28734',
      asset: 'DOT',
      category: 'crypto',
      sign: '',
      description: 'Inverse Polkadot',
      name: 'iDOT',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 20.6, upperLimit: 30.9, lowerLimit: 10.3 },
    },
    {
      feed: '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01',
      asset: 'REN',
      category: 'crypto',
      sign: '',
      description: 'Inverse Ren',
      name: 'iREN',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 0.7, upperLimit: 1.05, lowerLimit: 0.35 },
    },
    {
      feed: '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5',
      asset: 'COMP',
      category: 'crypto',
      sign: '',
      description: 'Inverse Compound',
      name: 'iCOMP',
      subclass: 'PurgeableSynth',
      inverted: { entryPoint: 393, upperLimit: 589.5, lowerLimit: 196.5 },
    },
  ],
}
