export { endpoint as backed } from './backed'
export { endpoint as eurr } from './eurr'
export { endpoint as gift } from './gift'
export { endpoint as mco2 } from './mco2'
export { endpoint as stbt } from './stbt'
export { endpoint as usdr } from './usdr'
