/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

interface FuturesMarketFactoryInterface extends ethers.utils.Interface {
  functions: {
    'accumulatedProtocolFee()': FunctionFragment
    'accumulatedSettlementFees(address)': FunctionFragment
    'addOutcomesToGroup(uint256,string[],uint256[][])': FunctionFragment
    'burnShares(uint256,uint256,address)': FunctionFragment
    'calcCost(uint256)': FunctionFragment
    'calcShares(uint256)': FunctionFragment
    'claimManyWinnings(uint256[],address)': FunctionFragment
    'claimProtocolFees()': FunctionFragment
    'claimSettlementFees(address)': FunctionFragment
    'claimWinnings(uint256,address)': FunctionFragment
    'collateral()': FunctionFragment
    'feePot()': FunctionFragment
    'finalizeGroup(uint256)': FunctionFragment
    'getGroup(uint256)': FunctionFragment
    'getGroupByIndex(uint256)': FunctionFragment
    'getMarket(uint256)': FunctionFragment
    'getOwner()': FunctionFragment
    'getVersion()': FunctionFragment
    'groupCount()': FunctionFragment
    'initializeGroup(uint256,string,string,uint256,string)': FunctionFragment
    'isMarketResolved(uint256)': FunctionFragment
    'linkNode()': FunctionFragment
    'listOfMarketGroups(uint256)': FunctionFragment
    'marketCount()': FunctionFragment
    'marketGroups(uint256)': FunctionFragment
    'mintShares(uint256,uint256,address)': FunctionFragment
    'protocol()': FunctionFragment
    'protocolFee()': FunctionFragment
    'resolveGroup(uint256,uint256)': FunctionFragment
    'resolveMarketAsNo(uint256)': FunctionFragment
    'setLinkNode(address)': FunctionFragment
    'setProtocol(address,bool)': FunctionFragment
    'setProtocolFee(uint256)': FunctionFragment
    'setSettlementFee(uint256)': FunctionFragment
    'setStakerFee(uint256)': FunctionFragment
    'settlementFee()': FunctionFragment
    'shareFactor()': FunctionFragment
    'stakerFee()': FunctionFragment
    'transferOwnership(address)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'accumulatedProtocolFee', values?: undefined): string
  encodeFunctionData(functionFragment: 'accumulatedSettlementFees', values: [string]): string
  encodeFunctionData(
    functionFragment: 'addOutcomesToGroup',
    values: [BigNumberish, string[], BigNumberish[][]],
  ): string
  encodeFunctionData(
    functionFragment: 'burnShares',
    values: [BigNumberish, BigNumberish, string],
  ): string
  encodeFunctionData(functionFragment: 'calcCost', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'calcShares', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'claimManyWinnings',
    values: [BigNumberish[], string],
  ): string
  encodeFunctionData(functionFragment: 'claimProtocolFees', values?: undefined): string
  encodeFunctionData(functionFragment: 'claimSettlementFees', values: [string]): string
  encodeFunctionData(functionFragment: 'claimWinnings', values: [BigNumberish, string]): string
  encodeFunctionData(functionFragment: 'collateral', values?: undefined): string
  encodeFunctionData(functionFragment: 'feePot', values?: undefined): string
  encodeFunctionData(functionFragment: 'finalizeGroup', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getGroup', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getGroupByIndex', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getMarket', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string
  encodeFunctionData(functionFragment: 'getVersion', values?: undefined): string
  encodeFunctionData(functionFragment: 'groupCount', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'initializeGroup',
    values: [BigNumberish, string, string, BigNumberish, string],
  ): string
  encodeFunctionData(functionFragment: 'isMarketResolved', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'linkNode', values?: undefined): string
  encodeFunctionData(functionFragment: 'listOfMarketGroups', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'marketCount', values?: undefined): string
  encodeFunctionData(functionFragment: 'marketGroups', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'mintShares',
    values: [BigNumberish, BigNumberish, string],
  ): string
  encodeFunctionData(functionFragment: 'protocol', values?: undefined): string
  encodeFunctionData(functionFragment: 'protocolFee', values?: undefined): string
  encodeFunctionData(functionFragment: 'resolveGroup', values: [BigNumberish, BigNumberish]): string
  encodeFunctionData(functionFragment: 'resolveMarketAsNo', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'setLinkNode', values: [string]): string
  encodeFunctionData(functionFragment: 'setProtocol', values: [string, boolean]): string
  encodeFunctionData(functionFragment: 'setProtocolFee', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'setSettlementFee', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'setStakerFee', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'settlementFee', values?: undefined): string
  encodeFunctionData(functionFragment: 'shareFactor', values?: undefined): string
  encodeFunctionData(functionFragment: 'stakerFee', values?: undefined): string
  encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string

  decodeFunctionResult(functionFragment: 'accumulatedProtocolFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'accumulatedSettlementFees', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'addOutcomesToGroup', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'burnShares', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'calcCost', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'calcShares', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'claimManyWinnings', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'claimProtocolFees', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'claimSettlementFees', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'claimWinnings', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'collateral', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'feePot', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'finalizeGroup', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getGroup', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getGroupByIndex', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getVersion', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'groupCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'initializeGroup', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isMarketResolved', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'linkNode', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'listOfMarketGroups', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'marketCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'marketGroups', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'mintShares', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'protocol', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'protocolFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'resolveGroup', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'resolveMarketAsNo', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setLinkNode', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setProtocol', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setProtocolFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setSettlementFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setStakerFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'settlementFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'shareFactor', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'stakerFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result

  events: {
    'GroupCreated(uint256,uint256,uint256,string)': EventFragment
    'GroupMarketAdded(uint256,uint256,string)': EventFragment
    'GroupReady(uint256)': EventFragment
    'GroupResolved(uint256,bool)': EventFragment
    'LinkNodeChanged(address)': EventFragment
    'MarketActivated(uint256)': EventFragment
    'MarketCreated(uint256,string[],uint256[])': EventFragment
    'MarketResolved(uint256,address,uint256,string)': EventFragment
    'SharesBurned(uint256,uint256,address)': EventFragment
    'SharesMinted(uint256,uint256,address)': EventFragment
    'WinningsClaimed(uint256,address,uint256,string,uint256,uint256,uint256,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'GroupCreated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'GroupMarketAdded'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'GroupReady'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'GroupResolved'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'LinkNodeChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'MarketActivated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'MarketCreated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'MarketResolved'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'SharesBurned'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'SharesMinted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'WinningsClaimed'): EventFragment
}

export class FuturesMarketFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: FuturesMarketFactoryInterface

  functions: {
    accumulatedProtocolFee(overrides?: CallOverrides): Promise<[BigNumber]>

    'accumulatedProtocolFee()'(overrides?: CallOverrides): Promise<[BigNumber]>

    accumulatedSettlementFees(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>

    'accumulatedSettlementFees(address)'(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>

    addOutcomesToGroup(
      _groupId: BigNumberish,
      _marketNames: string[],
      _odds: BigNumberish[][],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'addOutcomesToGroup(uint256,string[],uint256[][])'(
      _groupId: BigNumberish,
      _marketNames: string[],
      _odds: BigNumberish[][],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    burnShares(
      _id: BigNumberish,
      _sharesToBurn: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'burnShares(uint256,uint256,address)'(
      _id: BigNumberish,
      _sharesToBurn: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    calcCost(_shares: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    'calcCost(uint256)'(_shares: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    calcShares(_collateralIn: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    'calcShares(uint256)'(
      _collateralIn: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>

    claimManyWinnings(
      _ids: BigNumberish[],
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'claimManyWinnings(uint256[],address)'(
      _ids: BigNumberish[],
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    claimProtocolFees(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'claimProtocolFees()'(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    claimSettlementFees(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'claimSettlementFees(address)'(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    claimWinnings(
      _id: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'claimWinnings(uint256,address)'(
      _id: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    collateral(overrides?: CallOverrides): Promise<[string]>

    'collateral()'(overrides?: CallOverrides): Promise<[string]>

    feePot(overrides?: CallOverrides): Promise<[string]>

    'feePot()'(overrides?: CallOverrides): Promise<[string]>

    finalizeGroup(
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'finalizeGroup(uint256)'(
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    getGroup(
      _groupId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        },
      ]
    >

    'getGroup(uint256)'(
      _groupId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        },
      ]
    >

    getGroupByIndex(
      _index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        },
        BigNumber,
      ] & {
        _group: [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        }
        _groupId: BigNumber
      }
    >

    'getGroupByIndex(uint256)'(
      _index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        },
        BigNumber,
      ] & {
        _group: [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        }
        _groupId: BigNumber
      }
    >

    getMarket(
      _id: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [
          string,
          string[],
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          boolean,
        ] & {
          settlementAddress: string
          shareTokens: string[]
          winner: string
          winnerIndex: BigNumber
          settlementFee: BigNumber
          protocolFee: BigNumber
          stakerFee: BigNumber
          creationTimestamp: BigNumber
          initialOdds: BigNumber[]
          active: boolean
        },
      ]
    >

    'getMarket(uint256)'(
      _id: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [
          string,
          string[],
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber[],
          boolean,
        ] & {
          settlementAddress: string
          shareTokens: string[]
          winner: string
          winnerIndex: BigNumber
          settlementFee: BigNumber
          protocolFee: BigNumber
          stakerFee: BigNumber
          creationTimestamp: BigNumber
          initialOdds: BigNumber[]
          active: boolean
        },
      ]
    >

    getOwner(overrides?: CallOverrides): Promise<[string]>

    'getOwner()'(overrides?: CallOverrides): Promise<[string]>

    getVersion(overrides?: CallOverrides): Promise<[string]>

    'getVersion()'(overrides?: CallOverrides): Promise<[string]>

    groupCount(overrides?: CallOverrides): Promise<[BigNumber]>

    'groupCount()'(overrides?: CallOverrides): Promise<[BigNumber]>

    initializeGroup(
      _groupId: BigNumberish,
      _groupName: string,
      _invalidMarketName: string,
      _endTime: BigNumberish,
      _category: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'initializeGroup(uint256,string,string,uint256,string)'(
      _groupId: BigNumberish,
      _groupName: string,
      _invalidMarketName: string,
      _endTime: BigNumberish,
      _category: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    isMarketResolved(_id: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>

    'isMarketResolved(uint256)'(_id: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>

    linkNode(overrides?: CallOverrides): Promise<[string]>

    'linkNode()'(overrides?: CallOverrides): Promise<[string]>

    listOfMarketGroups(arg0: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    'listOfMarketGroups(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>

    marketCount(overrides?: CallOverrides): Promise<[BigNumber]>

    'marketCount()'(overrides?: CallOverrides): Promise<[BigNumber]>

    marketGroups(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [number, string, BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      }
    >

    'marketGroups(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [number, string, BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      }
    >

    mintShares(
      _id: BigNumberish,
      _shareToMint: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'mintShares(uint256,uint256,address)'(
      _id: BigNumberish,
      _shareToMint: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    protocol(overrides?: CallOverrides): Promise<[string]>

    'protocol()'(overrides?: CallOverrides): Promise<[string]>

    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>

    'protocolFee()'(overrides?: CallOverrides): Promise<[BigNumber]>

    resolveGroup(
      _groupId: BigNumberish,
      _winningMarketIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'resolveGroup(uint256,uint256)'(
      _groupId: BigNumberish,
      _winningMarketIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    resolveMarketAsNo(
      _marketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'resolveMarketAsNo(uint256)'(
      _marketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    setLinkNode(
      _newLinkNode: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'setLinkNode(address)'(
      _newLinkNode: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    setProtocol(
      _newProtocol: string,
      _claimFirst: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'setProtocol(address,bool)'(
      _newProtocol: string,
      _claimFirst: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    setProtocolFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'setProtocolFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    setSettlementFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'setSettlementFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    setStakerFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'setStakerFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    settlementFee(overrides?: CallOverrides): Promise<[BigNumber]>

    'settlementFee()'(overrides?: CallOverrides): Promise<[BigNumber]>

    shareFactor(overrides?: CallOverrides): Promise<[BigNumber]>

    'shareFactor()'(overrides?: CallOverrides): Promise<[BigNumber]>

    stakerFee(overrides?: CallOverrides): Promise<[BigNumber]>

    'stakerFee()'(overrides?: CallOverrides): Promise<[BigNumber]>

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    'transferOwnership(address)'(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>
  }

  accumulatedProtocolFee(overrides?: CallOverrides): Promise<BigNumber>

  'accumulatedProtocolFee()'(overrides?: CallOverrides): Promise<BigNumber>

  accumulatedSettlementFees(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

  'accumulatedSettlementFees(address)'(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

  addOutcomesToGroup(
    _groupId: BigNumberish,
    _marketNames: string[],
    _odds: BigNumberish[][],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'addOutcomesToGroup(uint256,string[],uint256[][])'(
    _groupId: BigNumberish,
    _marketNames: string[],
    _odds: BigNumberish[][],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  burnShares(
    _id: BigNumberish,
    _sharesToBurn: BigNumberish,
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'burnShares(uint256,uint256,address)'(
    _id: BigNumberish,
    _sharesToBurn: BigNumberish,
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  calcCost(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  'calcCost(uint256)'(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  calcShares(_collateralIn: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  'calcShares(uint256)'(_collateralIn: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  claimManyWinnings(
    _ids: BigNumberish[],
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'claimManyWinnings(uint256[],address)'(
    _ids: BigNumberish[],
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  claimProtocolFees(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'claimProtocolFees()'(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  claimSettlementFees(
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'claimSettlementFees(address)'(
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  claimWinnings(
    _id: BigNumberish,
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'claimWinnings(uint256,address)'(
    _id: BigNumberish,
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  collateral(overrides?: CallOverrides): Promise<string>

  'collateral()'(overrides?: CallOverrides): Promise<string>

  feePot(overrides?: CallOverrides): Promise<string>

  'feePot()'(overrides?: CallOverrides): Promise<string>

  finalizeGroup(
    _groupId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'finalizeGroup(uint256)'(
    _groupId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  getGroup(
    _groupId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
      status: number
      name: string
      markets: BigNumber[]
      marketNames: string[]
      invalidMarket: BigNumber
      invalidMarketName: string
      endTime: BigNumber
      category: string
    }
  >

  'getGroup(uint256)'(
    _groupId: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
      status: number
      name: string
      markets: BigNumber[]
      marketNames: string[]
      invalidMarket: BigNumber
      invalidMarketName: string
      endTime: BigNumber
      category: string
    }
  >

  getGroupByIndex(
    _index: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [
      [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        markets: BigNumber[]
        marketNames: string[]
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      },
      BigNumber,
    ] & {
      _group: [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        markets: BigNumber[]
        marketNames: string[]
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      }
      _groupId: BigNumber
    }
  >

  'getGroupByIndex(uint256)'(
    _index: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [
      [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        markets: BigNumber[]
        marketNames: string[]
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      },
      BigNumber,
    ] & {
      _group: [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        markets: BigNumber[]
        marketNames: string[]
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      }
      _groupId: BigNumber
    }
  >

  getMarket(
    _id: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [
      string,
      string[],
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber[],
      boolean,
    ] & {
      settlementAddress: string
      shareTokens: string[]
      winner: string
      winnerIndex: BigNumber
      settlementFee: BigNumber
      protocolFee: BigNumber
      stakerFee: BigNumber
      creationTimestamp: BigNumber
      initialOdds: BigNumber[]
      active: boolean
    }
  >

  'getMarket(uint256)'(
    _id: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [
      string,
      string[],
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber[],
      boolean,
    ] & {
      settlementAddress: string
      shareTokens: string[]
      winner: string
      winnerIndex: BigNumber
      settlementFee: BigNumber
      protocolFee: BigNumber
      stakerFee: BigNumber
      creationTimestamp: BigNumber
      initialOdds: BigNumber[]
      active: boolean
    }
  >

  getOwner(overrides?: CallOverrides): Promise<string>

  'getOwner()'(overrides?: CallOverrides): Promise<string>

  getVersion(overrides?: CallOverrides): Promise<string>

  'getVersion()'(overrides?: CallOverrides): Promise<string>

  groupCount(overrides?: CallOverrides): Promise<BigNumber>

  'groupCount()'(overrides?: CallOverrides): Promise<BigNumber>

  initializeGroup(
    _groupId: BigNumberish,
    _groupName: string,
    _invalidMarketName: string,
    _endTime: BigNumberish,
    _category: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'initializeGroup(uint256,string,string,uint256,string)'(
    _groupId: BigNumberish,
    _groupName: string,
    _invalidMarketName: string,
    _endTime: BigNumberish,
    _category: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  isMarketResolved(_id: BigNumberish, overrides?: CallOverrides): Promise<boolean>

  'isMarketResolved(uint256)'(_id: BigNumberish, overrides?: CallOverrides): Promise<boolean>

  linkNode(overrides?: CallOverrides): Promise<string>

  'linkNode()'(overrides?: CallOverrides): Promise<string>

  listOfMarketGroups(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  'listOfMarketGroups(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  marketCount(overrides?: CallOverrides): Promise<BigNumber>

  'marketCount()'(overrides?: CallOverrides): Promise<BigNumber>

  marketGroups(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [number, string, BigNumber, string, BigNumber, string] & {
      status: number
      name: string
      invalidMarket: BigNumber
      invalidMarketName: string
      endTime: BigNumber
      category: string
    }
  >

  'marketGroups(uint256)'(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [number, string, BigNumber, string, BigNumber, string] & {
      status: number
      name: string
      invalidMarket: BigNumber
      invalidMarketName: string
      endTime: BigNumber
      category: string
    }
  >

  mintShares(
    _id: BigNumberish,
    _shareToMint: BigNumberish,
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'mintShares(uint256,uint256,address)'(
    _id: BigNumberish,
    _shareToMint: BigNumberish,
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  protocol(overrides?: CallOverrides): Promise<string>

  'protocol()'(overrides?: CallOverrides): Promise<string>

  protocolFee(overrides?: CallOverrides): Promise<BigNumber>

  'protocolFee()'(overrides?: CallOverrides): Promise<BigNumber>

  resolveGroup(
    _groupId: BigNumberish,
    _winningMarketIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'resolveGroup(uint256,uint256)'(
    _groupId: BigNumberish,
    _winningMarketIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  resolveMarketAsNo(
    _marketId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'resolveMarketAsNo(uint256)'(
    _marketId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  setLinkNode(
    _newLinkNode: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'setLinkNode(address)'(
    _newLinkNode: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  setProtocol(
    _newProtocol: string,
    _claimFirst: boolean,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'setProtocol(address,bool)'(
    _newProtocol: string,
    _claimFirst: boolean,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  setProtocolFee(
    _newFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'setProtocolFee(uint256)'(
    _newFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  setSettlementFee(
    _newFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'setSettlementFee(uint256)'(
    _newFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  setStakerFee(
    _newFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'setStakerFee(uint256)'(
    _newFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  settlementFee(overrides?: CallOverrides): Promise<BigNumber>

  'settlementFee()'(overrides?: CallOverrides): Promise<BigNumber>

  shareFactor(overrides?: CallOverrides): Promise<BigNumber>

  'shareFactor()'(overrides?: CallOverrides): Promise<BigNumber>

  stakerFee(overrides?: CallOverrides): Promise<BigNumber>

  'stakerFee()'(overrides?: CallOverrides): Promise<BigNumber>

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  'transferOwnership(address)'(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  callStatic: {
    accumulatedProtocolFee(overrides?: CallOverrides): Promise<BigNumber>

    'accumulatedProtocolFee()'(overrides?: CallOverrides): Promise<BigNumber>

    accumulatedSettlementFees(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    'accumulatedSettlementFees(address)'(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    addOutcomesToGroup(
      _groupId: BigNumberish,
      _marketNames: string[],
      _odds: BigNumberish[][],
      overrides?: CallOverrides,
    ): Promise<void>

    'addOutcomesToGroup(uint256,string[],uint256[][])'(
      _groupId: BigNumberish,
      _marketNames: string[],
      _odds: BigNumberish[][],
      overrides?: CallOverrides,
    ): Promise<void>

    burnShares(
      _id: BigNumberish,
      _sharesToBurn: BigNumberish,
      _receiver: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    'burnShares(uint256,uint256,address)'(
      _id: BigNumberish,
      _sharesToBurn: BigNumberish,
      _receiver: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    calcCost(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'calcCost(uint256)'(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    calcShares(_collateralIn: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'calcShares(uint256)'(
      _collateralIn: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    claimManyWinnings(
      _ids: BigNumberish[],
      _receiver: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    'claimManyWinnings(uint256[],address)'(
      _ids: BigNumberish[],
      _receiver: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    claimProtocolFees(overrides?: CallOverrides): Promise<BigNumber>

    'claimProtocolFees()'(overrides?: CallOverrides): Promise<BigNumber>

    claimSettlementFees(_receiver: string, overrides?: CallOverrides): Promise<BigNumber>

    'claimSettlementFees(address)'(_receiver: string, overrides?: CallOverrides): Promise<BigNumber>

    claimWinnings(
      _id: BigNumberish,
      _receiver: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    'claimWinnings(uint256,address)'(
      _id: BigNumberish,
      _receiver: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    collateral(overrides?: CallOverrides): Promise<string>

    'collateral()'(overrides?: CallOverrides): Promise<string>

    feePot(overrides?: CallOverrides): Promise<string>

    'feePot()'(overrides?: CallOverrides): Promise<string>

    finalizeGroup(_groupId: BigNumberish, overrides?: CallOverrides): Promise<void>

    'finalizeGroup(uint256)'(_groupId: BigNumberish, overrides?: CallOverrides): Promise<void>

    getGroup(
      _groupId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        markets: BigNumber[]
        marketNames: string[]
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      }
    >

    'getGroup(uint256)'(
      _groupId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        markets: BigNumber[]
        marketNames: string[]
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      }
    >

    getGroupByIndex(
      _index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        },
        BigNumber,
      ] & {
        _group: [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        }
        _groupId: BigNumber
      }
    >

    'getGroupByIndex(uint256)'(
      _index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        },
        BigNumber,
      ] & {
        _group: [number, string, BigNumber[], string[], BigNumber, string, BigNumber, string] & {
          status: number
          name: string
          markets: BigNumber[]
          marketNames: string[]
          invalidMarket: BigNumber
          invalidMarketName: string
          endTime: BigNumber
          category: string
        }
        _groupId: BigNumber
      }
    >

    getMarket(
      _id: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        string,
        string[],
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber[],
        boolean,
      ] & {
        settlementAddress: string
        shareTokens: string[]
        winner: string
        winnerIndex: BigNumber
        settlementFee: BigNumber
        protocolFee: BigNumber
        stakerFee: BigNumber
        creationTimestamp: BigNumber
        initialOdds: BigNumber[]
        active: boolean
      }
    >

    'getMarket(uint256)'(
      _id: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [
        string,
        string[],
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber[],
        boolean,
      ] & {
        settlementAddress: string
        shareTokens: string[]
        winner: string
        winnerIndex: BigNumber
        settlementFee: BigNumber
        protocolFee: BigNumber
        stakerFee: BigNumber
        creationTimestamp: BigNumber
        initialOdds: BigNumber[]
        active: boolean
      }
    >

    getOwner(overrides?: CallOverrides): Promise<string>

    'getOwner()'(overrides?: CallOverrides): Promise<string>

    getVersion(overrides?: CallOverrides): Promise<string>

    'getVersion()'(overrides?: CallOverrides): Promise<string>

    groupCount(overrides?: CallOverrides): Promise<BigNumber>

    'groupCount()'(overrides?: CallOverrides): Promise<BigNumber>

    initializeGroup(
      _groupId: BigNumberish,
      _groupName: string,
      _invalidMarketName: string,
      _endTime: BigNumberish,
      _category: string,
      overrides?: CallOverrides,
    ): Promise<void>

    'initializeGroup(uint256,string,string,uint256,string)'(
      _groupId: BigNumberish,
      _groupName: string,
      _invalidMarketName: string,
      _endTime: BigNumberish,
      _category: string,
      overrides?: CallOverrides,
    ): Promise<void>

    isMarketResolved(_id: BigNumberish, overrides?: CallOverrides): Promise<boolean>

    'isMarketResolved(uint256)'(_id: BigNumberish, overrides?: CallOverrides): Promise<boolean>

    linkNode(overrides?: CallOverrides): Promise<string>

    'linkNode()'(overrides?: CallOverrides): Promise<string>

    listOfMarketGroups(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'listOfMarketGroups(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    marketCount(overrides?: CallOverrides): Promise<BigNumber>

    'marketCount()'(overrides?: CallOverrides): Promise<BigNumber>

    marketGroups(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [number, string, BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      }
    >

    'marketGroups(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [number, string, BigNumber, string, BigNumber, string] & {
        status: number
        name: string
        invalidMarket: BigNumber
        invalidMarketName: string
        endTime: BigNumber
        category: string
      }
    >

    mintShares(
      _id: BigNumberish,
      _shareToMint: BigNumberish,
      _receiver: string,
      overrides?: CallOverrides,
    ): Promise<void>

    'mintShares(uint256,uint256,address)'(
      _id: BigNumberish,
      _shareToMint: BigNumberish,
      _receiver: string,
      overrides?: CallOverrides,
    ): Promise<void>

    protocol(overrides?: CallOverrides): Promise<string>

    'protocol()'(overrides?: CallOverrides): Promise<string>

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>

    'protocolFee()'(overrides?: CallOverrides): Promise<BigNumber>

    resolveGroup(
      _groupId: BigNumberish,
      _winningMarketIndex: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>

    'resolveGroup(uint256,uint256)'(
      _groupId: BigNumberish,
      _winningMarketIndex: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>

    resolveMarketAsNo(_marketId: BigNumberish, overrides?: CallOverrides): Promise<void>

    'resolveMarketAsNo(uint256)'(_marketId: BigNumberish, overrides?: CallOverrides): Promise<void>

    setLinkNode(_newLinkNode: string, overrides?: CallOverrides): Promise<void>

    'setLinkNode(address)'(_newLinkNode: string, overrides?: CallOverrides): Promise<void>

    setProtocol(
      _newProtocol: string,
      _claimFirst: boolean,
      overrides?: CallOverrides,
    ): Promise<void>

    'setProtocol(address,bool)'(
      _newProtocol: string,
      _claimFirst: boolean,
      overrides?: CallOverrides,
    ): Promise<void>

    setProtocolFee(_newFee: BigNumberish, overrides?: CallOverrides): Promise<void>

    'setProtocolFee(uint256)'(_newFee: BigNumberish, overrides?: CallOverrides): Promise<void>

    setSettlementFee(_newFee: BigNumberish, overrides?: CallOverrides): Promise<void>

    'setSettlementFee(uint256)'(_newFee: BigNumberish, overrides?: CallOverrides): Promise<void>

    setStakerFee(_newFee: BigNumberish, overrides?: CallOverrides): Promise<void>

    'setStakerFee(uint256)'(_newFee: BigNumberish, overrides?: CallOverrides): Promise<void>

    settlementFee(overrides?: CallOverrides): Promise<BigNumber>

    'settlementFee()'(overrides?: CallOverrides): Promise<BigNumber>

    shareFactor(overrides?: CallOverrides): Promise<BigNumber>

    'shareFactor()'(overrides?: CallOverrides): Promise<BigNumber>

    stakerFee(overrides?: CallOverrides): Promise<BigNumber>

    'stakerFee()'(overrides?: CallOverrides): Promise<BigNumber>

    transferOwnership(_newOwner: string, overrides?: CallOverrides): Promise<boolean>

    'transferOwnership(address)'(_newOwner: string, overrides?: CallOverrides): Promise<boolean>
  }

  filters: {
    GroupCreated(
      id: BigNumberish | null,
      endTime: null,
      invalidMarketId: null,
      invalidMarketName: null,
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, string],
      {
        id: BigNumber
        endTime: BigNumber
        invalidMarketId: BigNumber
        invalidMarketName: string
      }
    >

    GroupMarketAdded(
      groupId: BigNumberish | null,
      marketId: null,
      marketName: null,
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { groupId: BigNumber; marketId: BigNumber; marketName: string }
    >

    GroupReady(id: BigNumberish | null): TypedEventFilter<[BigNumber], { id: BigNumber }>

    GroupResolved(
      id: BigNumberish | null,
      valid: null,
    ): TypedEventFilter<[BigNumber, boolean], { id: BigNumber; valid: boolean }>

    LinkNodeChanged(newLinkNode: null): TypedEventFilter<[string], { newLinkNode: string }>

    MarketActivated(id: null): TypedEventFilter<[BigNumber], { id: BigNumber }>

    MarketCreated(
      id: null,
      names: null,
      initialOdds: null,
    ): TypedEventFilter<
      [BigNumber, string[], BigNumber[]],
      { id: BigNumber; names: string[]; initialOdds: BigNumber[] }
    >

    MarketResolved(
      id: null,
      winner: null,
      winnerIndex: null,
      winnerName: null,
    ): TypedEventFilter<
      [BigNumber, string, BigNumber, string],
      {
        id: BigNumber
        winner: string
        winnerIndex: BigNumber
        winnerName: string
      }
    >

    SharesBurned(
      id: null,
      amount: null,
      receiver: null,
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { id: BigNumber; amount: BigNumber; receiver: string }
    >

    SharesMinted(
      id: null,
      amount: null,
      receiver: null,
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { id: BigNumber; amount: BigNumber; receiver: string }
    >

    WinningsClaimed(
      id: null,
      winningOutcome: null,
      winningIndex: null,
      winningName: null,
      amount: null,
      settlementFee: null,
      payout: null,
      receiver: string | null,
    ): TypedEventFilter<
      [BigNumber, string, BigNumber, string, BigNumber, BigNumber, BigNumber, string],
      {
        id: BigNumber
        winningOutcome: string
        winningIndex: BigNumber
        winningName: string
        amount: BigNumber
        settlementFee: BigNumber
        payout: BigNumber
        receiver: string
      }
    >
  }

  estimateGas: {
    accumulatedProtocolFee(overrides?: CallOverrides): Promise<BigNumber>

    'accumulatedProtocolFee()'(overrides?: CallOverrides): Promise<BigNumber>

    accumulatedSettlementFees(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    'accumulatedSettlementFees(address)'(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    addOutcomesToGroup(
      _groupId: BigNumberish,
      _marketNames: string[],
      _odds: BigNumberish[][],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'addOutcomesToGroup(uint256,string[],uint256[][])'(
      _groupId: BigNumberish,
      _marketNames: string[],
      _odds: BigNumberish[][],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    burnShares(
      _id: BigNumberish,
      _sharesToBurn: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'burnShares(uint256,uint256,address)'(
      _id: BigNumberish,
      _sharesToBurn: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    calcCost(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'calcCost(uint256)'(_shares: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    calcShares(_collateralIn: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'calcShares(uint256)'(
      _collateralIn: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    claimManyWinnings(
      _ids: BigNumberish[],
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'claimManyWinnings(uint256[],address)'(
      _ids: BigNumberish[],
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    claimProtocolFees(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'claimProtocolFees()'(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    claimSettlementFees(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'claimSettlementFees(address)'(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    claimWinnings(
      _id: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'claimWinnings(uint256,address)'(
      _id: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    collateral(overrides?: CallOverrides): Promise<BigNumber>

    'collateral()'(overrides?: CallOverrides): Promise<BigNumber>

    feePot(overrides?: CallOverrides): Promise<BigNumber>

    'feePot()'(overrides?: CallOverrides): Promise<BigNumber>

    finalizeGroup(
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'finalizeGroup(uint256)'(
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    getGroup(_groupId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getGroup(uint256)'(_groupId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getGroupByIndex(_index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getGroupByIndex(uint256)'(_index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getMarket(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getMarket(uint256)'(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getOwner(overrides?: CallOverrides): Promise<BigNumber>

    'getOwner()'(overrides?: CallOverrides): Promise<BigNumber>

    getVersion(overrides?: CallOverrides): Promise<BigNumber>

    'getVersion()'(overrides?: CallOverrides): Promise<BigNumber>

    groupCount(overrides?: CallOverrides): Promise<BigNumber>

    'groupCount()'(overrides?: CallOverrides): Promise<BigNumber>

    initializeGroup(
      _groupId: BigNumberish,
      _groupName: string,
      _invalidMarketName: string,
      _endTime: BigNumberish,
      _category: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'initializeGroup(uint256,string,string,uint256,string)'(
      _groupId: BigNumberish,
      _groupName: string,
      _invalidMarketName: string,
      _endTime: BigNumberish,
      _category: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    isMarketResolved(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'isMarketResolved(uint256)'(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    linkNode(overrides?: CallOverrides): Promise<BigNumber>

    'linkNode()'(overrides?: CallOverrides): Promise<BigNumber>

    listOfMarketGroups(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'listOfMarketGroups(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    marketCount(overrides?: CallOverrides): Promise<BigNumber>

    'marketCount()'(overrides?: CallOverrides): Promise<BigNumber>

    marketGroups(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'marketGroups(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    mintShares(
      _id: BigNumberish,
      _shareToMint: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'mintShares(uint256,uint256,address)'(
      _id: BigNumberish,
      _shareToMint: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    protocol(overrides?: CallOverrides): Promise<BigNumber>

    'protocol()'(overrides?: CallOverrides): Promise<BigNumber>

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>

    'protocolFee()'(overrides?: CallOverrides): Promise<BigNumber>

    resolveGroup(
      _groupId: BigNumberish,
      _winningMarketIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'resolveGroup(uint256,uint256)'(
      _groupId: BigNumberish,
      _winningMarketIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    resolveMarketAsNo(
      _marketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'resolveMarketAsNo(uint256)'(
      _marketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    setLinkNode(
      _newLinkNode: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'setLinkNode(address)'(
      _newLinkNode: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    setProtocol(
      _newProtocol: string,
      _claimFirst: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'setProtocol(address,bool)'(
      _newProtocol: string,
      _claimFirst: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    setProtocolFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'setProtocolFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    setSettlementFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'setSettlementFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    setStakerFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'setStakerFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    settlementFee(overrides?: CallOverrides): Promise<BigNumber>

    'settlementFee()'(overrides?: CallOverrides): Promise<BigNumber>

    shareFactor(overrides?: CallOverrides): Promise<BigNumber>

    'shareFactor()'(overrides?: CallOverrides): Promise<BigNumber>

    stakerFee(overrides?: CallOverrides): Promise<BigNumber>

    'stakerFee()'(overrides?: CallOverrides): Promise<BigNumber>

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    'transferOwnership(address)'(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>
  }

  populateTransaction: {
    accumulatedProtocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'accumulatedProtocolFee()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    accumulatedSettlementFees(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    'accumulatedSettlementFees(address)'(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    addOutcomesToGroup(
      _groupId: BigNumberish,
      _marketNames: string[],
      _odds: BigNumberish[][],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'addOutcomesToGroup(uint256,string[],uint256[][])'(
      _groupId: BigNumberish,
      _marketNames: string[],
      _odds: BigNumberish[][],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    burnShares(
      _id: BigNumberish,
      _sharesToBurn: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'burnShares(uint256,uint256,address)'(
      _id: BigNumberish,
      _sharesToBurn: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    calcCost(_shares: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'calcCost(uint256)'(
      _shares: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    calcShares(
      _collateralIn: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    'calcShares(uint256)'(
      _collateralIn: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    claimManyWinnings(
      _ids: BigNumberish[],
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'claimManyWinnings(uint256[],address)'(
      _ids: BigNumberish[],
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    claimProtocolFees(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'claimProtocolFees()'(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    claimSettlementFees(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'claimSettlementFees(address)'(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    claimWinnings(
      _id: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'claimWinnings(uint256,address)'(
      _id: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    collateral(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'collateral()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    feePot(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'feePot()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    finalizeGroup(
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'finalizeGroup(uint256)'(
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    getGroup(_groupId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getGroup(uint256)'(
      _groupId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getGroupByIndex(_index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getGroupByIndex(uint256)'(
      _index: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getMarket(_id: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getMarket(uint256)'(
      _id: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getOwner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getVersion()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    groupCount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'groupCount()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    initializeGroup(
      _groupId: BigNumberish,
      _groupName: string,
      _invalidMarketName: string,
      _endTime: BigNumberish,
      _category: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'initializeGroup(uint256,string,string,uint256,string)'(
      _groupId: BigNumberish,
      _groupName: string,
      _invalidMarketName: string,
      _endTime: BigNumberish,
      _category: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    isMarketResolved(_id: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'isMarketResolved(uint256)'(
      _id: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    linkNode(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'linkNode()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    listOfMarketGroups(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'listOfMarketGroups(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    marketCount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'marketCount()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    marketGroups(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'marketGroups(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    mintShares(
      _id: BigNumberish,
      _shareToMint: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'mintShares(uint256,uint256,address)'(
      _id: BigNumberish,
      _shareToMint: BigNumberish,
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    protocol(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'protocol()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'protocolFee()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    resolveGroup(
      _groupId: BigNumberish,
      _winningMarketIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'resolveGroup(uint256,uint256)'(
      _groupId: BigNumberish,
      _winningMarketIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    resolveMarketAsNo(
      _marketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'resolveMarketAsNo(uint256)'(
      _marketId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    setLinkNode(
      _newLinkNode: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'setLinkNode(address)'(
      _newLinkNode: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    setProtocol(
      _newProtocol: string,
      _claimFirst: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'setProtocol(address,bool)'(
      _newProtocol: string,
      _claimFirst: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    setProtocolFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'setProtocolFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    setSettlementFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'setSettlementFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    setStakerFee(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'setStakerFee(uint256)'(
      _newFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    settlementFee(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'settlementFee()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    shareFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'shareFactor()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    stakerFee(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'stakerFee()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    'transferOwnership(address)'(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>
  }
}
