export const EC_REGISTRY_ABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: '_address', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'mode', type: 'bool' },
    ],
    name: 'contractControllerEvent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'string', name: '_name', type: 'string' },
      { indexed: false, internalType: 'address', name: '_address', type: 'address' },
      { indexed: false, internalType: 'uint8', name: '_traitType', type: 'uint8' },
      { indexed: false, internalType: 'uint16', name: '_start', type: 'uint16' },
      { indexed: false, internalType: 'uint16', name: '_end', type: 'uint16' },
    ],
    name: 'newTraitEvent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint16', name: '_traitId', type: 'uint16' },
      { indexed: true, internalType: 'uint16', name: '_tokenId', type: 'uint16' },
      { indexed: false, internalType: 'bool', name: 'mode', type: 'bool' },
    ],
    name: 'tokenTraitChangeEvent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: '_address', type: 'address' }],
    name: 'traitControllerEvent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint16', name: '_id', type: 'uint16' }],
    name: 'updateTraitDataEvent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint16', name: '_id', type: 'uint16' },
      { indexed: false, internalType: 'string', name: '_name', type: 'string' },
      { indexed: false, internalType: 'address', name: '_address', type: 'address' },
      { indexed: false, internalType: 'uint8', name: '_traitType', type: 'uint8' },
      { indexed: false, internalType: 'uint16', name: '_start', type: 'uint16' },
      { indexed: false, internalType: 'uint16', name: '_end', type: 'uint16' },
    ],
    name: 'updateTraitEvent',
    type: 'event',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint16', name: 'id', type: 'uint16' },
          { internalType: 'uint8', name: 'traitType', type: 'uint8' },
          { internalType: 'uint16', name: 'start', type: 'uint16' },
          { internalType: 'uint16', name: 'end', type: 'uint16' },
          { internalType: 'address', name: 'implementer', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
        ],
        internalType: 'struct ECRegistryV3.traitStruct[]',
        name: '_newTraits',
        type: 'tuple[]',
      },
    ],
    name: 'addTrait',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_addr', type: 'address' },
      { internalType: 'uint16', name: 'traitID', type: 'uint16' },
    ],
    name: 'addressCanModifyTrait',
    outputs: [{ internalType: 'bool', name: 'result', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_addr', type: 'address' },
      { internalType: 'uint16[]', name: 'traitIDs', type: 'uint16[]' },
    ],
    name: 'addressCanModifyTraits',
    outputs: [{ internalType: 'bool', name: 'result', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint16', name: '_offset', type: 'uint16' }],
    name: 'getByteAndBit',
    outputs: [
      { internalType: 'uint16', name: '_byte', type: 'uint16' },
      { internalType: 'uint8', name: '_bit', type: 'uint8' },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_index', type: 'uint256' }],
    name: 'getContractControllerAt',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_addr', type: 'address' }],
    name: 'getContractControllerContains',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getContractControllerLength',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'traitId', type: 'uint16' },
      { internalType: 'uint8', name: '_page', type: 'uint8' },
      { internalType: 'uint16', name: '_perPage', type: 'uint16' },
    ],
    name: 'getData',
    outputs: [{ internalType: 'uint8[]', name: '', type: 'uint8[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint16', name: 'traitID', type: 'uint16' }],
    name: 'getImplementer',
    outputs: [{ internalType: 'address', name: 'implementer', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint16', name: 'tokenId', type: 'uint16' }],
    name: 'getTokenData',
    outputs: [{ internalType: 'uint8[]', name: '', type: 'uint8[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_addr', type: 'address' }],
    name: 'getTraitControllerAccessData',
    outputs: [{ internalType: 'uint8[]', name: '', type: 'uint8[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTraits',
    outputs: [
      {
        components: [
          { internalType: 'uint16', name: 'id', type: 'uint16' },
          { internalType: 'uint8', name: 'traitType', type: 'uint8' },
          { internalType: 'uint16', name: 'start', type: 'uint16' },
          { internalType: 'uint16', name: 'end', type: 'uint16' },
          { internalType: 'address', name: 'implementer', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
        ],
        internalType: 'struct ECRegistryV3.traitStruct[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'traitID', type: 'uint16' },
      { internalType: 'uint16', name: 'tokenId', type: 'uint16' },
    ],
    name: 'hasTrait',
    outputs: [{ internalType: 'bool', name: 'result', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_controller', type: 'address' },
      { internalType: 'bool', name: '_mode', type: 'bool' },
    ],
    name: 'setContractController',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'traitId', type: 'uint16' },
      { internalType: 'uint16[]', name: '_ids', type: 'uint16[]' },
      { internalType: 'uint8[]', name: '_data', type: 'uint8[]' },
    ],
    name: 'setData',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'traitID', type: 'uint16' },
      { internalType: 'uint16', name: 'tokenId', type: 'uint16' },
      { internalType: 'bool', name: '_value', type: 'bool' },
    ],
    name: 'setTrait',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_addr', type: 'address' },
      { internalType: 'uint16', name: 'traitID', type: 'uint16' },
      { internalType: 'bool', name: '_value', type: 'bool' },
    ],
    name: 'setTraitControllerAccess',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_addr', type: 'address' },
      { internalType: 'uint8[]', name: '_data', type: 'uint8[]' },
    ],
    name: 'setTraitControllerAccessData',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'traitID', type: 'uint16' },
      { internalType: 'uint16[]', name: 'tokenIds', type: 'uint16[]' },
      { internalType: 'bool[]', name: '_value', type: 'bool[]' },
    ],
    name: 'setTraitOnMultiple',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: '', type: 'uint16' },
      { internalType: 'uint16', name: '', type: 'uint16' },
    ],
    name: 'tokenData',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint8', name: '', type: 'uint8' },
    ],
    name: 'traitControllerAccess',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'traitControllerByAddress',
    outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    name: 'traitControllerById',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'traitControllerCount',
    outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'traitCount',
    outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    name: 'traits',
    outputs: [
      { internalType: 'uint16', name: 'id', type: 'uint16' },
      { internalType: 'uint8', name: 'traitType', type: 'uint8' },
      { internalType: 'uint16', name: 'start', type: 'uint16' },
      { internalType: 'uint16', name: 'end', type: 'uint16' },
      { internalType: 'address', name: 'implementer', type: 'address' },
      { internalType: 'string', name: 'name', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: '_traitId', type: 'uint16' },
      { internalType: 'string', name: '_name', type: 'string' },
      { internalType: 'address', name: '_implementer', type: 'address' },
      { internalType: 'uint8', name: '_traitType', type: 'uint8' },
      { internalType: 'uint16', name: '_start', type: 'uint16' },
      { internalType: 'uint16', name: '_end', type: 'uint16' },
    ],
    name: 'updateTrait',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
