import nock from 'nock'

export const mockCryptoResponseSuccess = (): nock.Scope =>
  nock('https://api.coinranking.com/v2', {
    encodedQueryParams: true,
    reqheaders: {
      'x-access-token': 'fake-api-key',
    },
  })
    .get('/coins')
    .query({ 'symbols[]': 'ETH' })
    .reply(
      200,
      () => ({
        status: 'success',
        data: {
          stats: {
            total: 2,
            totalCoins: 12443,
            totalMarkets: 22970,
            totalExchanges: 173,
            totalMarketCap: '2851820248983',
            total24hVolume: '128082207195',
          },
          coins: [
            {
              uuid: 'razxDUgYGNAdQ',
              symbol: 'ETH',
              name: 'Ethereum',
              color: '#3C3C3D',
              iconUrl: 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg',
              marketCap: '527538906196',
              price: '4478.930333561968',
              listedAt: 1438905600,
              tier: 1,
              change: '4.59',
              rank: 2,
              sparkline: [
                '4282.1804199846228637180000',
                '4295.9820933572436686440000',
                '4338.0415746961392639740000',
                '4317.4246601886649788100000',
                '4296.0931736628041592430000',
                '4317.6363325631844686940000',
                '4319.5656864028767274890000',
                '4315.0492875427621272280000',
                '4319.3435285958741908900000',
                '4312.8379293033577666440000',
                '4309.9339113747802206040000',
                '4335.5094937050709057660000',
                '4351.1826227419480188020000',
                '4361.2776132439523819370000',
                '4362.3590272312213170420000',
                '4344.6618847237498360710000',
                '4355.0108360480565010600000',
                '4434.9508778240489888020000',
                '4440.9039538669308358670000',
                '4432.1808277294489703950000',
                '4444.4011631659664527740000',
                '4467.2186533493298884390000',
                '4475.3444958315847831110000',
                '4497.1013469323828725430000',
                '4495.1474082460385223070000',
                '4479.8274332723585633240000',
                '4478.9303335619675063580000',
              ],
              lowVolume: false,
              coinrankingUrl: 'https://coinranking.com/coin/razxDUgYGNAdQ+ethereum-eth',
              '24hVolume': '16855138984',
              btcPrice: '0.07068440870606915',
            },
            {
              uuid: 'z_D3NLkrkPDW',
              symbol: 'ETH',
              name: 'ETH Light',
              color: null,
              iconUrl: 'https://cdn.coinranking.com/W_LV9_LV_/eth-light.svg',
              marketCap: null,
              price: '0.000039624511925286',
              listedAt: 1545060300,
              tier: 3,
              change: '0',
              rank: 5675,
              sparkline: [
                '0.0000396245119252860000',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                '0.0000396245119252860000',
              ],
              lowVolume: false,
              coinrankingUrl: 'https://coinranking.com/coin/z_D3NLkrkPDW+ethlight-eth',
              '24hVolume': null,
              btcPrice: '6.53373113e-10',
            },
          ],
        },
      }),
      [
        'Content-Type',
        'application/json',
        'Connection',
        'close',
        'Vary',
        'Accept-Encoding',
        'Vary',
        'Origin',
      ],
    )

export const mockReferenceCurrenciesSuccess = (): nock.Scope =>
  nock('https://api.coinranking.com/v2', {
    encodedQueryParams: true,
    reqheaders: {
      'x-access-token': 'fake-api-key',
    },
  })
    .get('/reference-currencies')
    .reply(
      200,
      () => ({
        status: 'success',
        data: {
          stats: { total: 12643 },
          currencies: [
            {
              uuid: 'yhjMzLPhuIDl',
              type: 'fiat',
              iconUrl: 'https://cdn.coinranking.com/kz6a7w6vF/usd.svg',
              name: 'US Dollar',
              symbol: 'USD',
              sign: '$',
            },
            {
              uuid: '5k-_VTxqtCEI',
              type: 'fiat',
              iconUrl: 'https://cdn.coinranking.com/fz3P5lsJY/eur.svg',
              name: 'Euro',
              symbol: 'EUR',
              sign: '€',
            },
            {
              uuid: 'K4iOZMuz76cc',
              type: 'fiat',
              iconUrl: 'https://cdn.coinranking.com/tDtpsWiy9/malaysian-ringgit.svg',
              name: 'Malaysian Ringgit',
              symbol: 'MYR',
              sign: 'RM',
            },
            {
              uuid: 'ETQIOVR_rqox',
              type: 'fiat',
              iconUrl: null,
              name: 'Indonesian Rupiah',
              symbol: 'IDR',
              sign: 'Rp',
            },
            {
              uuid: 'OEomm4hQzk_M',
              type: 'fiat',
              iconUrl: null,
              name: 'Australian Dollar',
              symbol: 'AUD',
              sign: '$',
            },
            {
              uuid: '6mUvpzCc2lFo',
              type: 'fiat',
              iconUrl: null,
              name: 'Indian Rupee',
              symbol: 'INR',
              sign: '₹',
            },
            {
              uuid: 'Hokyui45Z38f',
              type: 'fiat',
              iconUrl: 'https://cdn.coinranking.com/2wzSKKrBp/gbp.svg',
              name: 'British Pound Sterling',
              symbol: 'GBP',
              sign: '£',
            },
            {
              uuid: '_4s0A3Uuu5ML',
              type: 'fiat',
              iconUrl: null,
              name: 'Canadian dollar',
              symbol: 'CAD',
              sign: 'C$',
            },
            {
              uuid: '5IPIPRCm3C6O',
              type: 'fiat',
              iconUrl: 'https://cdn.coinranking.com/Mn61ZjrQr/south-african-rand.svg',
              name: 'South African Rand',
              symbol: 'ZAR',
              sign: 'R',
            },
            {
              uuid: 'eXMH_Xz9YUhh',
              type: 'fiat',
              iconUrl: 'https://cdn.coinranking.com/lJBdOdg9C/chf.svg',
              name: 'Swiss franc',
              symbol: 'CHF',
              sign: null,
            },
            {
              uuid: '45LL9_IxSQg-',
              type: 'fiat',
              iconUrl: null,
              name: 'Brunei Dollar',
              symbol: 'BND',
              sign: null,
            },
            {
              uuid: 'znnRJjGM4nVb',
              type: 'fiat',
              iconUrl: 'https://cdn.coinranking.com/4oA0RNI9W/nigerian-naira.svg',
              name: 'Nigerian Naira',
              symbol: 'NGN',
              sign: null,
            },
            {
              uuid: 'n5fpnvMGNsOS',
              type: 'fiat',
              iconUrl: null,
              name: 'Brazilian Real',
              symbol: 'BRL',
              sign: 'R$',
            },
            {
              uuid: 'Dk5T6J0UtCUA',
              type: 'fiat',
              iconUrl: 'https://cdn.coinranking.com/4k26GEE3f/turkish-lira.svg',
              name: 'Turkish Lira',
              symbol: 'TRY',
              sign: '₺',
            },
            {
              uuid: 'YnFzw1gLeOb1',
              type: 'denominator',
              iconUrl: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
              name: 'Satoshi',
              symbol: 'SATOSHI',
              sign: 'Ș',
            },
            {
              uuid: 'Qwsogvtv82FCd',
              type: 'coin',
              iconUrl: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
              name: 'Bitcoin',
              symbol: 'BTC',
              sign: 'Ƀ',
            },
            {
              uuid: 'razxDUgYGNAdQ',
              type: 'coin',
              iconUrl: 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg',
              name: 'Ethereum',
              symbol: 'ETH',
              sign: 'Ξ',
            },
            {
              uuid: 'WcwrkfNI4FUAe',
              type: 'coin',
              iconUrl: 'https://cdn.coinranking.com/B1N19L_dZ/bnb.svg',
              name: 'Binance Coin',
              symbol: 'BNB',
              sign: null,
            },
            {
              uuid: 'HIVsRcGKkPFtW',
              type: 'coin',
              iconUrl: 'https://cdn.coinranking.com/mgHqwlCLj/usdt.svg',
              name: 'Tether USD',
              symbol: 'USDT',
              sign: null,
            },
            {
              uuid: 'zNZHO_Sjf',
              type: 'coin',
              iconUrl: 'https://cdn.coinranking.com/yvUG4Qex5/solana.svg',
              name: 'Solana',
              symbol: 'SOL',
              sign: null,
            },
          ],
        },
      }),
      [
        'Content-Type',
        'application/json',
        'Connection',
        'close',
        'Vary',
        'Accept-Encoding',
        'Vary',
        'Origin',
      ],
    )

export const mockCryptoResponseFailure = (): nock.Scope =>
  nock('https://api.coinranking.com/v2', {
    encodedQueryParams: true,
    reqheaders: {
      'x-access-token': 'fake-api-key',
    },
  })
    .get('/coins')
    .query({ 'symbols[]': 'non-existing' })
    .reply(
      200,
      () => ({
        status: 'success',
        data: {
          stats: {
            total: 0,
            totalCoins: 12459,
            totalMarkets: 22791,
            totalExchanges: 171,
            totalMarketCap: '2858152707225',
            total24hVolume: '135029952342',
          },
          coins: [],
        },
      }),
      [
        'Content-Type',
        'application/json',
        'Connection',
        'close',
        'Vary',
        'Accept-Encoding',
        'Vary',
        'Origin',
      ],
    )

export const mockTotalMarketCapSuccess = (): nock.Scope =>
  nock('https://api.coinranking.com/v2', {
    encodedQueryParams: true,
    reqheaders: {
      'x-access-token': 'fake-api-key',
    },
  })
    .get('/stats')
    .reply(
      200,
      {
        status: 'success',
        data: {
          referenceCurrencyRate: 1,
          totalCoins: 23349,
          totalMarkets: 37921,
          totalExchanges: 179,
          totalMarketCap: '1139638848309',
          total24hVolume: '85309476474',
          btcDominance: 41.393155263964395,
          bestCoins: [
            {
              uuid: 'fmHk13Rqw',
              symbol: 'FLOKI*',
              name: 'FLOKI',
              iconUrl: 'https://cdn.coinranking.com/Yfn5I1O01/10804.png',
              coinrankingUrl: 'https://coinranking.com/coin/fmHk13Rqw+floki-floki',
            },
            {
              uuid: '08CsQa-Ov',
              symbol: 'WEMIX',
              name: 'WEMIX TOKEN',
              iconUrl: 'https://cdn.coinranking.com/1N84MQsoO/7548.png',
              coinrankingUrl: 'https://coinranking.com/coin/08CsQa-Ov+wemixtoken-wemix',
            },
            {
              uuid: 'jrP7Ptsct',
              symbol: 'ACH**',
              name: 'Alchemy Pay',
              iconUrl: 'https://cdn.coinranking.com/tkKQoiNEr/alchemypay.svg',
              coinrankingUrl: 'https://coinranking.com/coin/jrP7Ptsct+alchemypay-ach',
            },
          ],
          newestCoins: [
            {
              uuid: 'ZO8YGJCio',
              symbol: 'HASHTAG',
              name: 'Hashtag United F.C Fan Token',
              iconUrl: 'https://cdn.coinranking.com/FYBQpoUyV/HASH.PNG',
              coinrankingUrl:
                'https://coinranking.com/coin/ZO8YGJCio+hashtagunitedfcfantoken-hashtag',
            },
            {
              uuid: 'BYg5FxSE-',
              symbol: 'FLAME',
              name: 'Flame Chain',
              iconUrl: 'https://cdn.coinranking.com/mv2256upC/FLAME_LOGO.png',
              coinrankingUrl: 'https://coinranking.com/coin/BYg5FxSE-+flamechain-flame',
            },
            {
              uuid: 'EK1DC7MeO',
              symbol: 'SFIL',
              name: 'Super File Coin',
              iconUrl: 'https://cdn.coinranking.com/n15BzWVX7/SFIL_LOGO.png',
              coinrankingUrl: 'https://coinranking.com/coin/EK1DC7MeO+superfilecoin-sfil',
            },
          ],
        },
      },
      [
        'Content-Type',
        'application/json',
        'Connection',
        'close',
        'Vary',
        'Accept-Encoding',
        'Vary',
        'Origin',
      ],
    )
