import nock from 'nock'

export const mockSportsDataProviderResponse = () => {
  nock('https://fly.sportsdata.io:443', { encodedQueryParams: true })
    .get('/v3/nba/stats/json/PlayerGameStatsByPlayer/2021-OCT-11/20002528')
    .query({ key: '6cd20300b9eb40e093ee5cc30cda1007' })
    .reply(
      200,
      {
        StatID: 900479,
        TeamID: 2,
        PlayerID: 20002528,
        SeasonType: 2,
        Season: 2022,
        Name: 'LaMelo Ball',
        Team: 'CHA',
        Position: 'PG',
        Started: 1,
        FanDuelSalary: 6000,
        DraftKingsSalary: 6500,
        FantasyDataSalary: 6500,
        YahooSalary: null,
        InjuryStatus: null,
        InjuryBodyPart: null,
        InjuryStartDate: null,
        InjuryNotes: null,
        FanDuelPosition: 'PG',
        DraftKingsPosition: 'PG',
        YahooPosition: null,
        OpponentRank: 7,
        OpponentPositionRank: 3,
        GlobalTeamID: 20000002,
        FantasyDraftSalary: null,
        FantasyDraftPosition: null,
        GameID: 17944,
        OpponentID: 4,
        Opponent: 'MIA',
        Day: '2021-10-11T00:00:00',
        DateTime: '2021-10-11T19:30:00',
        HomeOrAway: 'AWAY',
        IsGameOver: true,
        GlobalGameID: 20017944,
        GlobalOpponentID: 20000004,
        Updated: '2021-10-14T03:15:14',
        Games: 1,
        FantasyPoints: 41.1,
        Minutes: 26,
        Seconds: 29,
        FieldGoalsMade: 7,
        FieldGoalsAttempted: 14,
        FieldGoalsPercentage: 50,
        EffectiveFieldGoalsPercentage: 57.1,
        TwoPointersMade: 5,
        TwoPointersAttempted: 6,
        TwoPointersPercentage: 83.3,
        ThreePointersMade: 2,
        ThreePointersAttempted: 8,
        ThreePointersPercentage: 25,
        FreeThrowsMade: 3,
        FreeThrowsAttempted: 3,
        FreeThrowsPercentage: 100,
        OffensiveRebounds: 2,
        DefensiveRebounds: 6,
        Rebounds: 8,
        OffensiveReboundsPercentage: 8.62,
        DefensiveReboundsPercentage: 20.91,
        TotalReboundsPercentage: 15.42,
        Assists: 9,
        Steals: 1,
        BlockedShots: 0,
        Turnovers: 3,
        PersonalFouls: 4,
        Points: 19,
        TrueShootingAttempts: 15.32,
        TrueShootingPercentage: 61.3,
        PlayerEfficiencyRating: 32.97,
        AssistsPercentage: 59.71,
        StealsPercentage: 1.83,
        BlocksPercentage: 0,
        TurnOversPercentage: 16.37,
        UsageRatePercentage: 30.53,
        FantasyPointsFanDuel: 42.1,
        FantasyPointsDraftKings: 44,
        FantasyPointsYahoo: 42.1,
        PlusMinus: 10,
        DoubleDoubles: 0,
        TripleDoubles: 0,
        FantasyPointsFantasyDraft: 44,
        IsClosed: true,
        LineupConfirmed: false,
        LineupStatus: 'Active',
      },
      [
        'Connection',
        'close',
        'Content-Length',
        '1884',
        'Content-Type',
        'application/json; charset=utf-8',
        'Last-Modified',
        'Thu, 14 Oct 2021 17:43:58 GMT',
        'X-AspNet-Version',
        '4.0.30319',
        'Cache-Control',
        'must-revalidate, max-age=5',
        'Via',
        '1.1 varnish, 1.1 varnish',
        'Fastly-Restarts',
        '1',
        'Accept-Ranges',
        'bytes',
        'Date',
        'Thu, 14 Oct 2021 17:43:59 GMT',
        'Age',
        '0',
        'X-Served-By',
        'cache-pwk12227-PWK, cache-sea4475-SEA',
        'X-Cache',
        'MISS, MISS',
        'X-Cache-Hits',
        '0, 0',
        'X-Timer',
        'S1634233439.905292,VS0,VE123',
        'Vary',
        'x-subtier, Accept-Encoding',
        'Access-Control-Allow-Origin',
        '*',
      ],
    )
}
