const HTTP_OK = 200
const HTTP_GATEWAY_TIMEOUT = 504

import nock from 'nock'
import { PartialAdapterResponse } from '@chainlink/external-adapter-framework/util'

const { MockEvent } = require('mocksse') // eslint-disable-line

type IOPair = {
  request: { data: any }
  response: Partial<PartialAdapterResponse> & { statusCode: number }
}

export const IO: IOPair[] = [
  {
    request: { data: { base: 'ETH', quote: 'USD' } },
    response: { data: { result: 111 }, result: 111, statusCode: HTTP_OK }, //TODO fix
  },
  // {
  //   request: { data: { base: 'WTICO', quote: 'USD' } },
  //   response: { data: { result: 111 }, result: 111, statusCode: HTTP_OK }, //TODO fix
  // },
  // {
  //   request: { data: { base: 'EUR', quote: 'USD' } },
  //   response: { data: { result: 111 }, result: 111, statusCode: HTTP_OK }, //TODO fix
  // },
  // {
  //   request: { data: { base: 'INR', quote: 'USD' } },
  //   response: { data: { result: 111 }, result: 111, statusCode: HTTP_OK }, //TODO fix
  // },
  // {
  //   request: { data: { base: 'IDR', quote: 'USD' } },
  //   response: { data: { result: 111 }, result: 111, statusCode: HTTP_OK }, //TODO fix
  // },
  // {
  //   request: { data: { base: 'XAU', quote: 'USD' } },
  //   response: { data: { result: 111 }, result: 111, statusCode: HTTP_OK }, //TODO fix
  // },
  // {
  //   request: { data: { base: 'USB10Y', quote: 'USD' } },
  //   response: { data: { result: 111 }, result: 111, statusCode: HTTP_OK }, //TODO fix
  // },
  // {
  //   request: { data: { base: 'SPX500', quote: 'USD' } },
  //   response: { data: { result: 111 }, result: 111, statusCode: HTTP_OK }, //TODO fix
  // },
  // {
  //   request: { data: { base: 'NONE', quote: 'USD' } },
  //   response: { statusCode: HTTP_GATEWAY_TIMEOUT },
  // },
]

export const mockSSE = () =>
  new MockEvent({
    url: 'https://stream-fxtrade.oanda.com/v3',
    setInterval: 100,
    responses: [
      {
        type: 'PRICE',
        time: '2023-02-09T10:12:30.956036112Z',
        bids: [{ price: '1632.45', liquidity: 20 }],
        asks: [{ price: '1635.79', liquidity: 20 }],
        closeoutBid: '1632.45',
        closeoutAsk: '1635.79',
        status: 'tradeable',
        tradeable: true,
        instrument: 'ETH_USD',
      },
      //TODO add other cases
      // {
      //   type: 'PRICE',
      //   time: '2023-02-09T10:12:31.495130342Z',
      //   bids: [{ price: '22699.6', liquidity: 20 }],
      //   asks: [{ price: '22748.3', liquidity: 20 }],
      //   closeoutBid: '22699.6',
      //   closeoutAsk: '22748.3',
      //   status: 'tradeable',
      //   tradeable: true,
      //   instrument: 'BTC_USD',
      // },
    ],
  })

export const mockRESTPrice = () =>
  nock('https://exchange-rates-api.oanda.com/v2/rates/spot.json')
    .post('?base=USD&quote=IDR')
    .times(1)
    .reply(HTTP_OK, {
      meta: {
        effective_params: {
          data_set: 'OANDA',
          base_currencies: ['USD'],
          quote_currencies: ['IDR'],
          decimal_places: null,
        },
        endpoint: 'spot',
        request_time: '2023-02-10T06:18:39+00:00',
        skipped_currency_pairs: [],
      },
      quotes: [
        {
          base_currency: 'USD',
          quote_currency: 'IDR',
          bid: '15161.9',
          ask: '15164.4',
          midpoint: '15163.2',
        },
      ],
    })
    .post('?base=USD&quote=INR')
    .times(1)
    .reply(HTTP_OK, {
      meta: {
        effective_params: {
          data_set: 'OANDA',
          base_currencies: ['USD'],
          quote_currencies: ['INR'],
          decimal_places: null,
        },
        endpoint: 'spot',
        request_time: '2023-02-10T06:23:08+00:00',
        skipped_currency_pairs: [],
      },
      quotes: [
        {
          base_currency: 'USD',
          quote_currency: 'INR',
          bid: '82.563',
          ask: '82.571',
          midpoint: '82.567',
        },
      ],
    })

export const mockRESTInstruments = () =>
  nock('https://api-fxtrade.oanda.com/v3/accounts/test-acct-id')
    .get('/instruments')
    .reply(HTTP_OK, {
      instruments: [
        {
          name: 'NZD_CHF',
          type: 'CURRENCY',
          displayName: 'NZD/CHF',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'ESPIX_EUR',
          type: 'CFD',
          displayName: 'Spain 35',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '500',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
          financing: {
            longRate: '-0.049',
            shortRate: '-0.001',
            financingDaysOfWeek: [
              {
                dayOfWeek: 'MONDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'TUESDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'WEDNESDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'THURSDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'FRIDAY',
                daysCharged: 3,
              },
              {
                dayOfWeek: 'SATURDAY',
                daysCharged: 0,
              },
              {
                dayOfWeek: 'SUNDAY',
                daysCharged: 0,
              },
            ],
          },
        },
        {
          name: 'CAD_CHF',
          type: 'CURRENCY',
          displayName: 'CAD/CHF',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAU_XAG',
          type: 'METAL',
          displayName: 'Gold/Silver',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '10000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'XPT_USD',
          type: 'CFD',
          displayName: 'Platinum',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '5000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'EUR_CZK',
          type: 'CURRENCY',
          displayName: 'EUR/CZK',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'JP225Y_JPY',
          type: 'CFD',
          displayName: 'Japan 225 (JPY)',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'XPD_USD',
          type: 'CFD',
          displayName: 'Palladium',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '5000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'USD_CAD',
          type: 'CURRENCY',
          displayName: 'USD/CAD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAU_USD',
          type: 'METAL',
          displayName: 'Gold',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'EUR_USD',
          type: 'CURRENCY',
          displayName: 'EUR/USD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'GBP_JPY',
          type: 'CURRENCY',
          displayName: 'GBP/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '50000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_TRY',
          type: 'CURRENCY',
          displayName: 'USD/TRY',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '10000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'DE30_EUR',
          type: 'CFD',
          displayName: 'Germany 30',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '1000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'CHF_HKD',
          type: 'CURRENCY',
          displayName: 'CHF/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'NZD_CAD',
          type: 'CURRENCY',
          displayName: 'NZD/CAD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'US30_USD',
          type: 'CFD',
          displayName: 'US Wall St 30',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '1000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'NL25_EUR',
          type: 'CFD',
          displayName: 'Netherlands 25',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '12000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'CHINAH_HKD',
          type: 'CFD',
          displayName: 'China H Shares',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '500',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
          financing: {
            longRate: '-0.0359',
            shortRate: '-0.0141',
            financingDaysOfWeek: [
              {
                dayOfWeek: 'MONDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'TUESDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'WEDNESDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'THURSDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'FRIDAY',
                daysCharged: 3,
              },
              {
                dayOfWeek: 'SATURDAY',
                daysCharged: 0,
              },
              {
                dayOfWeek: 'SUNDAY',
                daysCharged: 0,
              },
            ],
          },
        },
        {
          name: 'BTC_USD',
          type: 'CFD',
          displayName: 'Bitcoin',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 2,
          minimumTradeSize: '0.01',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '1000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CRYPTO',
            },
          ],
        },
        {
          name: 'EUR_TRY',
          type: 'CURRENCY',
          displayName: 'EUR/TRY',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '10000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_JPY',
          type: 'CURRENCY',
          displayName: 'USD/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'EUR_HKD',
          type: 'CURRENCY',
          displayName: 'EUR/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'GBP_HKD',
          type: 'CURRENCY',
          displayName: 'GBP/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAU_NZD',
          type: 'METAL',
          displayName: 'Gold/NZD',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'GBP_NZD',
          type: 'CURRENCY',
          displayName: 'GBP/NZD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'GBP_SGD',
          type: 'CURRENCY',
          displayName: 'GBP/SGD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_SEK',
          type: 'CURRENCY',
          displayName: 'USD/SEK',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'EUR_SGD',
          type: 'CURRENCY',
          displayName: 'EUR/SGD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAG_JPY',
          type: 'METAL',
          displayName: 'Silver/JPY',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'ETH_USD',
          type: 'CFD',
          displayName: 'Ether',
          pipLocation: -1,
          displayPrecision: 2,
          tradeUnitsPrecision: 2,
          minimumTradeSize: '0.01',
          maximumTrailingStopDistance: '1000.00',
          minimumTrailingStopDistance: '0.50',
          maximumPositionSize: '0',
          maximumOrderUnits: '10000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CRYPTO',
            },
          ],
        },
        {
          name: 'USD_HKD',
          type: 'CURRENCY',
          displayName: 'USD/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAG_HKD',
          type: 'METAL',
          displayName: 'Silver/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'XCU_USD',
          type: 'CFD',
          displayName: 'Copper',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '1500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
          ],
        },
        {
          name: 'XAU_JPY',
          type: 'METAL',
          displayName: 'Gold/JPY',
          pipLocation: 1,
          displayPrecision: 0,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100000',
          minimumTrailingStopDistance: '50',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'EUR_PLN',
          type: 'CURRENCY',
          displayName: 'EUR/PLN',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'SUGAR_USD',
          type: 'CFD',
          displayName: 'Sugar',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
          ],
        },
        {
          name: 'HKD_JPY',
          type: 'CURRENCY',
          displayName: 'HKD/JPY',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'CHF_ZAR',
          type: 'CURRENCY',
          displayName: 'CHF/ZAR',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'ZAR_JPY',
          type: 'CURRENCY',
          displayName: 'ZAR/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.005',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAU_HKD',
          type: 'METAL',
          displayName: 'Gold/HKD',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'AUD_CHF',
          type: 'CURRENCY',
          displayName: 'AUD/CHF',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'EUR_CHF',
          type: 'CURRENCY',
          displayName: 'EUR/CHF',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_MXN',
          type: 'CURRENCY',
          displayName: 'USD/MXN',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'GBP_USD',
          type: 'CURRENCY',
          displayName: 'GBP/USD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '50000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'BCH_USD',
          type: 'CFD',
          displayName: 'Bitcoin Cash',
          pipLocation: -1,
          displayPrecision: 2,
          tradeUnitsPrecision: 2,
          minimumTradeSize: '0.01',
          maximumTrailingStopDistance: '1000.00',
          minimumTrailingStopDistance: '0.50',
          maximumPositionSize: '0',
          maximumOrderUnits: '5000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CRYPTO',
            },
          ],
        },
        {
          name: 'XAG_AUD',
          type: 'METAL',
          displayName: 'Silver/AUD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'WTICO_USD',
          type: 'CFD',
          displayName: 'West Texas Oil',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
          ],
        },
        {
          name: 'AUD_HKD',
          type: 'CURRENCY',
          displayName: 'AUD/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'SGD_HKD',
          type: 'CURRENCY',
          displayName: 'SGD/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'AUD_SGD',
          type: 'CURRENCY',
          displayName: 'AUD/SGD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'US2000_USD',
          type: 'CFD',
          displayName: 'US Russ 2000',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '5000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'CN50_USD',
          type: 'CFD',
          displayName: 'China A50',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '500',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'NZD_JPY',
          type: 'CURRENCY',
          displayName: 'NZD/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USB02Y_USD',
          type: 'CFD',
          displayName: 'US 2Y T-Note',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '200000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'BOND',
            },
          ],
        },
        {
          name: 'EUR_NZD',
          type: 'CURRENCY',
          displayName: 'EUR/NZD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAU_SGD',
          type: 'METAL',
          displayName: 'Gold/SGD',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'USD_SAR',
          type: 'CURRENCY',
          displayName: 'USD/SAR',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'GBP_CAD',
          type: 'CURRENCY',
          displayName: 'GBP/CAD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'EUR_AUD',
          type: 'CURRENCY',
          displayName: 'EUR/AUD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'SGD_JPY',
          type: 'CURRENCY',
          displayName: 'SGD/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'TRY_JPY',
          type: 'CURRENCY',
          displayName: 'TRY/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'EUR_ZAR',
          type: 'CURRENCY',
          displayName: 'EUR/ZAR',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'AUD_JPY',
          type: 'CURRENCY',
          displayName: 'AUD/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'EUR_SEK',
          type: 'CURRENCY',
          displayName: 'EUR/SEK',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_SGD',
          type: 'CURRENCY',
          displayName: 'USD/SGD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_THB',
          type: 'CURRENCY',
          displayName: 'USD/THB',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'GBP_CHF',
          type: 'CURRENCY',
          displayName: 'GBP/CHF',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'GBP_AUD',
          type: 'CURRENCY',
          displayName: 'GBP/AUD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_PLN',
          type: 'CURRENCY',
          displayName: 'USD/PLN',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAG_EUR',
          type: 'METAL',
          displayName: 'Silver/EUR',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'LTC_USD',
          type: 'CFD',
          displayName: 'Litecoin',
          pipLocation: -1,
          displayPrecision: 2,
          tradeUnitsPrecision: 2,
          minimumTradeSize: '0.01',
          maximumTrailingStopDistance: '1000.00',
          minimumTrailingStopDistance: '0.50',
          maximumPositionSize: '0',
          maximumOrderUnits: '40000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CRYPTO',
            },
          ],
        },
        {
          name: 'HK33_HKD',
          type: 'CFD',
          displayName: 'Hong Kong 33',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '2000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'UK100_GBP',
          type: 'CFD',
          displayName: 'UK 100',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '500',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'USB05Y_USD',
          type: 'CFD',
          displayName: 'US 5Y T-Note',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '200000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'BOND',
            },
          ],
        },
        {
          name: 'EUR_NOK',
          type: 'CURRENCY',
          displayName: 'EUR/NOK',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'CH20_CHF',
          type: 'CFD',
          displayName: 'Switzerland 20',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '500',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
          financing: {
            longRate: '-0.0345',
            shortRate: '-0.0155',
            financingDaysOfWeek: [
              {
                dayOfWeek: 'MONDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'TUESDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'WEDNESDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'THURSDAY',
                daysCharged: 1,
              },
              {
                dayOfWeek: 'FRIDAY',
                daysCharged: 3,
              },
              {
                dayOfWeek: 'SATURDAY',
                daysCharged: 0,
              },
              {
                dayOfWeek: 'SUNDAY',
                daysCharged: 0,
              },
            ],
          },
        },
        {
          name: 'CAD_HKD',
          type: 'CURRENCY',
          displayName: 'CAD/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAU_CAD',
          type: 'METAL',
          displayName: 'Gold/CAD',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'CAD_JPY',
          type: 'CURRENCY',
          displayName: 'CAD/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_ZAR',
          type: 'CURRENCY',
          displayName: 'USD/ZAR',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAU_AUD',
          type: 'METAL',
          displayName: 'Gold/AUD',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'WHEAT_USD',
          type: 'CFD',
          displayName: 'Wheat',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '1000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
          ],
        },
        {
          name: 'NZD_SGD',
          type: 'CURRENCY',
          displayName: 'NZD/SGD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAU_CHF',
          type: 'METAL',
          displayName: 'Gold/CHF',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'DE10YB_EUR',
          type: 'CFD',
          displayName: 'Bund',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '150000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'BOND',
            },
          ],
        },
        {
          name: 'USD_HUF',
          type: 'CURRENCY',
          displayName: 'USD/HUF',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'EUR_CAD',
          type: 'CURRENCY',
          displayName: 'EUR/CAD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'NAS100_USD',
          type: 'CFD',
          displayName: 'US Nas 100',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '2000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'CAD_SGD',
          type: 'CURRENCY',
          displayName: 'CAD/SGD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'MBTC_USD',
          type: 'CFD',
          displayName: 'Mini Bitcoin',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '1000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CRYPTO',
            },
          ],
        },
        {
          name: 'GBP_ZAR',
          type: 'CURRENCY',
          displayName: 'GBP/ZAR',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAG_GBP',
          type: 'METAL',
          displayName: 'Silver/GBP',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'EUR_HUF',
          type: 'CURRENCY',
          displayName: 'EUR/HUF',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'AUD_NZD',
          type: 'CURRENCY',
          displayName: 'AUD/NZD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'FR40_EUR',
          type: 'CFD',
          displayName: 'France 40',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '1000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'USB30Y_USD',
          type: 'CFD',
          displayName: 'US T-Bond',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '200000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'BOND',
            },
          ],
        },
        {
          name: 'NZD_HKD',
          type: 'CURRENCY',
          displayName: 'NZD/HKD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'XAG_USD',
          type: 'METAL',
          displayName: 'Silver',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'CORN_USD',
          type: 'CFD',
          displayName: 'Corn',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '1500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
          ],
        },
        {
          name: 'USD_CHF',
          type: 'CURRENCY',
          displayName: 'USD/CHF',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'AUD_USD',
          type: 'CURRENCY',
          displayName: 'AUD/USD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_NOK',
          type: 'CURRENCY',
          displayName: 'USD/NOK',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'AU200_AUD',
          type: 'CFD',
          displayName: 'Australia 200',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '1250',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'SGD_CHF',
          type: 'CURRENCY',
          displayName: 'SGD/CHF',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'JP225_USD',
          type: 'CFD',
          displayName: 'Japan 225',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '750',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'USD_CZK',
          type: 'CURRENCY',
          displayName: 'USD/CZK',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'NZD_USD',
          type: 'CURRENCY',
          displayName: 'NZD/USD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'EUR_GBP',
          type: 'CURRENCY',
          displayName: 'EUR/GBP',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'AUD_CAD',
          type: 'CURRENCY',
          displayName: 'AUD/CAD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'UK10YB_GBP',
          type: 'CFD',
          displayName: 'UK 10Y Gilt',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'BOND',
            },
          ],
        },
        {
          name: 'SOYBN_USD',
          type: 'CFD',
          displayName: 'Soybeans',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '600000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
          ],
        },
        {
          name: 'EUR_DKK',
          type: 'CURRENCY',
          displayName: 'EUR/DKK',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'BCO_USD',
          type: 'CFD',
          displayName: 'Brent Crude Oil',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
          ],
        },
        {
          name: 'USD_DKK',
          type: 'CURRENCY',
          displayName: 'USD/DKK',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'SPX500_USD',
          type: 'CFD',
          displayName: 'US SPX 500',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '10000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'XAG_CHF',
          type: 'METAL',
          displayName: 'Silver/CHF',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'XAU_GBP',
          type: 'METAL',
          displayName: 'Gold/GBP',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'XAU_EUR',
          type: 'METAL',
          displayName: 'Gold/EUR',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '20000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'XAG_SGD',
          type: 'METAL',
          displayName: 'Silver/SGD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'XAG_NZD',
          type: 'METAL',
          displayName: 'Silver/NZD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'GBP_PLN',
          type: 'CURRENCY',
          displayName: 'GBP/PLN',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'USD_CNH',
          type: 'CURRENCY',
          displayName: 'USD/CNH',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'NATGAS_USD',
          type: 'CFD',
          displayName: 'Natural Gas',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '1000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
          ],
        },
        {
          name: 'SG30_SGD',
          type: 'CFD',
          displayName: 'Singapore 30',
          pipLocation: -1,
          displayPrecision: 2,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '1000.00',
          minimumTrailingStopDistance: '0.50',
          maximumPositionSize: '0',
          maximumOrderUnits: '2000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'USB10Y_USD',
          type: 'CFD',
          displayName: 'US 10Y T-Note',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '200000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'BOND',
            },
          ],
        },
        {
          name: 'EU50_EUR',
          type: 'CFD',
          displayName: 'Europe 50',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '3000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'XAG_CAD',
          type: 'METAL',
          displayName: 'Silver/CAD',
          pipLocation: -4,
          displayPrecision: 5,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '1.00000',
          minimumTrailingStopDistance: '0.00050',
          maximumPositionSize: '0',
          maximumOrderUnits: '500000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'COMMODITY',
            },
            {
              type: 'KID_ASSET_CLASS',
              name: 'METAL',
            },
          ],
        },
        {
          name: 'EUR_JPY',
          type: 'CURRENCY',
          displayName: 'EUR/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
        {
          name: 'TWIX_USD',
          type: 'CFD',
          displayName: 'Taiwan Index',
          pipLocation: 0,
          displayPrecision: 1,
          tradeUnitsPrecision: 1,
          minimumTradeSize: '0.1',
          maximumTrailingStopDistance: '10000.0',
          minimumTrailingStopDistance: '5.0',
          maximumPositionSize: '0',
          maximumOrderUnits: '10000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'INDEX',
            },
          ],
        },
        {
          name: 'CHF_JPY',
          type: 'CURRENCY',
          displayName: 'CHF/JPY',
          pipLocation: -2,
          displayPrecision: 3,
          tradeUnitsPrecision: 0,
          minimumTradeSize: '1',
          maximumTrailingStopDistance: '100.000',
          minimumTrailingStopDistance: '0.050',
          maximumPositionSize: '0',
          maximumOrderUnits: '100000000',
          marginRate: '1',
          guaranteedStopLossOrderMode: 'DISABLED',
          tags: [
            {
              type: 'ASSET_CLASS',
              name: 'CURRENCY',
            },
          ],
        },
      ],
      lastTransactionID: '2',
    })
    .persist()
