{
 "title": "EA Rate Limit",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Spent RL Credits per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rate_limit_credits_spent_total[5m]) * 60)"
    }
   ]
  },
  {
   "title": "Average Provider Response time in Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_execution_duration_seconds_sum{cache_hit=\"false\"}[5m]))\n/\nsum(rate(cache_execution_duration_seconds_count{cache_hit=\"false\"}[5m]))"
    }
   ]
  },
  {
   "title": "Provider Hits per minute/jobId",
   "type": "graph",
   "description": "Compares the requests per jobId that hit the provider. If Cache warmer is active, should make all the work while the warmer subscription is active",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rate_limit_credits_spent_total{}[5m]) * 60) by (job_run_id)"
    }
   ]
  },
  {
   "title": "Provider Hits per Feed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rate_limit_credits_spent_total[5m]) * 60) by (feed_id)"
    }
   ]
  },
  {
   "title": "Average Data Staleness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_data_staleness_seconds_sum[5m]))\n/\nsum(rate(cache_data_staleness_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Average Cache response time in Secs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_execution_duration_seconds_sum{cache_hit=\"true\"}[5m])) / sum(rate(cache_execution_duration_seconds_count{cache_hit=\"true\"}[5m]))"
    }
   ]
  }
 ]
}