#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

for line in $(git diff --cached --name-only)
do
  # Check for npm tokens and block commits if found
  if grep -qiE "npm_[A-Za-z0-9]{36}" "$line"; then
    echo "NPM token found in file \"$line\" staged for commit, remove it!"
    exit 1
  fi
done
