#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

STAGED_FILES=$(git diff --name-only --cached)

yarn generate:readme -f $STAGED_FILES
README_GENERATOR_EXIT_CODE=$?

if [ $README_GENERATOR_EXIT_CODE -ne 0 ]; then
    echo "README(s) could not be generated. Aborting commit."
    exit 1
else
    echo "README(s) generated successfully."
fi

yarn lint-staged
