name: Adapter changes accompanied by a changeset

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  # Changeset check
  adapter-change-has-changeset:
    name: Adapter changes accompanied by a changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check whether adapter change also has a changeset
        id: adapter_change_has_changeset
        run: ./.github/isvalidadapterchange.sh
