name: Auto update open PRs

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically update PR
        uses: smartcontractkit/update-pr-branch@612ec4916f57a7f79af534c6b7c9a8623f957a71 # v0.5.1
        with:
          token: ${{ secrets.AUTOREBASE_TOKEN }}
          base: 'main'
          required_approval_count: 1
          require_passed_checks: false
