name: Consume changesets

on:
  push:
    branches:
      - develop

jobs:
  consume-changesets:
    name: Consume changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Get release notes
        run: yarn get-release-notes

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          title: 'Consume changesets'
          commit: 'Consume changesets'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Repo
        run: yarn setup

      - name: Generate Documentation
        run: |
          yarn generate:master-list -v
          yarn generate:readme -a -v
          git add *
          yarn lint-staged
          git commit --amend --no-edit
          git push --force
          echo "README(s) generated successfully."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
