name: Consume changesets

on:
  push:
    branches:
      - develop

jobs:
  consume-changesets:
    name: Consume changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          title: Consume changesets
          commit: Consume changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
