name: Consume changesets

on:
  push:
    branches:
      - develop

jobs:
  consume-changesets:
    name: Consume changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          skip-setup: true
      - name: Get release notes
        run: yarn get-release-notes
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          title: 'Consume changesets'
          commit: 'Consume changesets'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger workflows in changesets PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yml',
              ref: 'changeset-release/develop'
            })
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'generate-readmes.yml',
              ref: 'changeset-release/develop'
            })
